ardriveapp/ardrive-web

- docs/private_drive_kdf_reference.dart
- lib/blocs/profile/profile_bloc.dart
- lib/blocs/profile/profile_state.dart
- lib/blocs/upload/upload_bloc.dart
- lib/blocs/upload/upload_event.dart
- lib/entities/drive_entity.dart
- lib/entities/entity.dart
- lib/entities/file_entity.dart
- lib/entities/folder_entity.dart
- lib/models/daos/drive_dao.dart
- lib/models/daos/drives_dao.dart
- lib/models/daos/profile_dao.dart
- lib/services/arweave_service.dart
- lib/services/crypto/cipher_key.dart
- lib/services/crypto/crypto.dart
- lib/services/crypto/entities.dart
- lib/services/crypto/keys.dart
- lib/services/crypto/utils.dart
- pubspec.lock
- pubspec.yaml
Refactor to use web cryptography apis on web.
> Refactor cryptography implementation

- assets/config/dev.json
- assets/config/prod.json
- lib/main.dart
- lib/services/arweave/arweave_service.dart
- lib/services/config/app_config.dart
- lib/services/config/config.dart
- lib/services/config/config_service.dart
- lib/services/services.dart
- pubspec.lock
- pubspec.yaml
Adds `ConfigService` for switching configurations between dev and prod environments.
Also changes to use `arweave.dev` for dev and `arweave.net` for prod.
> Add and use ConfigService

- lib/components/fs_entry_move_form.dart
- lib/main.dart
- lib/theme/theme.dart
- lib/views/profile_auth/profile_auth_view.dart
- Changes data table selection color.
- Changes text input caret color.
- Shares ListTileTheme globally.
> Tweak brand theme

- lib/app_shell.dart
- lib/blocs/profile/profile_cubit.dart
- lib/blocs/profile/profile_state.dart
- lib/main.dart
- lib/services/arweave/arweave_service.dart
- lib/theme/theme.dart
Allows the user to view their wallet balance and logout from their profile.
> Add user profile overlay

- lib/blocs/blocs.dart
- lib/blocs/fs_entry_activity/fs_entry_activity_cubit.dart
- lib/blocs/fs_entry_activity/fs_entry_activity_state.dart
- lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_state.dart
- lib/blocs/sync/sync_cubit.dart
- lib/entities/drive_entity.dart
- lib/entities/entity.dart
- lib/entities/file_entity.dart
- lib/entities/folder_entity.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/daos/drives_dao.dart
- lib/models/database/database.dart
- lib/models/file_entry.dart
- lib/models/file_revision.dart
- lib/models/folder_entry.dart
- lib/models/folder_revision.dart
- lib/models/models.dart
- lib/models/revision_action.dart
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/theme/theme.dart
This implements business logic for revision tracking of folders and files and surfaces said revisions in the UI.
This does not implement revision tracking for drives.
> Implement revision tracking

- lib/blocs/blocs.dart
- lib/blocs/file_download/file_download_cubit.dart
- lib/blocs/file_download/personal_file_download_cubit.dart
- lib/blocs/file_download/shared_file_download_cubit.dart
- lib/blocs/file_share/file_share_cubit.dart
- lib/blocs/file_share/file_share_state.dart
- lib/blocs/shared_file/shared_file_cubit.dart
- lib/blocs/shared_file/shared_file_state.dart
- lib/components/components.dart
- lib/components/file_download_dialog.dart
- lib/components/file_share_dialog.dart
- lib/entities/file_entity.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/pages/app_route_information_parser.dart
- lib/pages/app_route_path.dart
- lib/pages/app_router_delegate.dart
- lib/pages/drive_detail/components/drive_detail_actions_row.dart
- lib/pages/pages.dart
- lib/pages/shared_file/shared_file_page.dart
- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/FirstFileEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/LatestFileEntityWithId.graphql
- lib/theme/constants.dart
Enables users to share public and private files using a link.
> Add file sharing functionality

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/pr.yaml
- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- pubspec.lock
This PR moves us back to the Flutter dev channel which contains the latest fixes for Flutter web.
> chore: switch back to Flutter dev channel

- lib/blocs/fs_entry_move/fs_entry_move_cubit.dart
- lib/components/fs_entry_move_form.dart
[Issue 213](http://redmine.ardrive.io/issues/213)
> fix: update breadcrumb on folder move

- lib/app_shell.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the build error on the latest Flutter dev channel release.
It also bumps various dependencies and removes a workaround for a plugin bug.
> fix: web build failing

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- lib/services/arweave/arweave_service.dart
PR adds price in usd under AR cost
> feat: display usd price

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- lib/services/arweave/arweave_service.dart
This PR updates the upload dialog to reduce the number of decimals for the USD converted upload cost.
> ui: update USD converted cost display

- .github/workflows/deploy-prod.yaml
- README.md
- pubspec.lock
This PR adds some documentation regarding the release process to app.ardrive.io
> chore: add docs surrounding the release process

- lib/blocs/drive_attach/drive_attach_cubit.dart
- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/drive_share/drive_share_cubit.dart
- lib/components/app_drawer/app_drawer.dart
- lib/components/drive_attach_form.dart
- lib/pages/app_route_information_parser.dart
- lib/pages/app_route_path.dart
- lib/pages/app_router_delegate.dart
- pubspec.lock
Pass name through share link and attach drive automatically.
> feat: direct public drive attach

- lib/blocs/fs_entry_activity/fs_entry_activity_cubit.dart
- lib/blocs/sync/sync_cubit.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/drive_revision.dart
- lib/models/models.dart
- lib/models/queries/drive_queries.moor
- lib/models/tables/all.moor
- lib/models/tables/drive_revisions.moor
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
This PR adds tracking for drive revisions like what folders and files have.
> feat: track drive revisions

- lib/pages/app_router_delegate.dart
- lib/pages/shared_file/shared_file_page.dart
> fix: shared file page not showing

- lib/app_shell.dart
- lib/components/app_drawer/app_drawer.dart
[Issue](http://redmine.ardrive.io/issues/236)
> ui: added sync dialog as overlay to prevent interaction

- lib/blocs/file_download/file_download_cubit.dart
- lib/blocs/file_download/file_download_state.dart
- lib/blocs/file_download/personal_file_download_cubit.dart
- lib/blocs/file_download/shared_file_download_cubit.dart
- lib/components/file_download_dialog.dart
- pubspec.lock
- pubspec.yaml
Adds an abortDownload function to FileDownloadCubit which closes the connection.
>  feat/276 Abort HTTP requests with dio 

- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/daos/drive_dao/drive_order.dart
- lib/pages/drive_detail/components/drive_detail_data_table.dart
>  fix/179 Table Sorting 

- lib/components/app_drawer/app_drawer.dart
- lib/pages/drive_detail/components/drive_detail_data_table.dart
- lib/pages/drive_detail/drive_detail_page.dart
Make appdrawer scrollable
Make datatable scrollable without hiding actions
> fix/279 Cannot see drives in drive list

- pubspec.lock
- pubspec.yaml
Removed cryptography git dependency and upgrades crypto dependency override to 3.0.1
>  task/280-Remove-external-dependencies

- lib/components/profile_overlay.dart
- pubspec.lock
- pubspec.yaml
> nit: changed precision of ar displayed

- README.md
Added the steps I took to get the Flutter web app development environment setup on a fairly fresh MacOS installation.
> PE-13: Update dev environment setup in README

- lib/app_shell.dart
- lib/blocs/profile/profile_cubit.dart
- lib/blocs/profile_add/profile_add_cubit.dart
- lib/blocs/sync/sync_cubit.dart
- lib/pages/profile_auth/components/profile_auth_loading_screen.dart
- lib/pages/profile_auth/profile_auth_page.dart
Shows appropriate warning message based on wallet type.
> PE-45/Warn about user switching focus

- lib/l10n/app_es.arb
- lib/main.dart
Removes Spanish locale from supported locales files and removes app_es.arb
> Fix/PE-20 Remove Spanish Locale

- lib/blocs/profile_add/profile_add_cubit.dart
> PE-56/Fix loading when there is no ArConnect login

- lib/blocs/profile_add/profile_add_cubit.dart
Sets the profileType to JSON while picking a JSON wallet.
>  PE-88/Fix JSON login after ArConnect login

- lib/blocs/sync/sync_cubit.dart
Use document.visibilityState to detect if tab is hidden instead of document.hidden.
> PE-86/Resume sync after switching focus

- lib/blocs/sync/sync_cubit.dart
- lib/models/tables/drives.moor
- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/DriveEntityHistory.graphql
Adds back lastBlockHeight to fix ArDrive not syncing between instances.
> task(ardrive-web): Add lastBlockHeight to drive PE-87

- lib/models/database/database.dart
Schema version changed to 10 from 9
> task(ardrive-web): increment schema to 10 PE-111

- pubspec.yaml
> task(ardrive-web): Increment version to 1.1.3

- lib/blocs/sync/sync_cubit.dart
- lib/services/arweave/arweave_service.dart
> fix: filter drive entitites with owner PE-509

- lib/blocs/data_export/data_export_cubit.dart
- lib/blocs/data_export/data_export_state.dart
- lib/components/csv_export_dialog.dart
- lib/models/queries/drive_queries.moor
- lib/pages/drive_detail/components/drive_detail_actions_row.dart
- lib/pages/drive_detail/drive_detail_page.dart
- pubspec.lock
- pubspec.yaml
- test/blocs/data_export_cubit_test.dart
- test/snapshots/data_export_snapshot.dart
- test/utils/utils.dart
Exports the latest revisions of all files contained in a drive as a csv. Simply open the drive in the web app and click on the table icon next to the rename icon.
> feature: csv export of file data for a drive PE-668

- lib/blocs/sync/sync_cubit.dart
> refactor(sync): increase sync frequency to 5 min

- lib/blocs/sync/sync_cubit.dart
Only sync after context switch if time elapsed since last sync is greater than 5 minutes.
> PE 810 Add lastSync var

- lib/blocs/sync/sync_cubit.dart
Decouple ArConnect from main sync stream
> PE 788 Decouple ArConnect from Sync

- lib/blocs/upload/upload_cubit.dart
- lib/utils/bundles/next_fit_bundle_packer.dart
- test/utils/bundle_packer_test.dart
Adds a max data item count to bundle packing algo and related tests.
> PE 852 Add bundle data item limit

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
Adds a warning to stay on the tab during the upload process while using an arconnect wallet.
> refactor(ui): add upload warning for arconnect PE-863

- lib/blocs/drive_create/drive_create_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_state.dart
- lib/entities/drive_entity.dart
- lib/entities/entity.dart
- lib/models/database/database.dart
- lib/models/drive_revision.dart
- lib/models/tables/drive_revisions.moor
- lib/models/tables/drives.moor
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
Adds a bundledIn field for drive and shows drive tx id, root folder tx id and bundle tx id in info sheet.
> PE 766 Add bundled in for drives

- lib/blocs/ghost_fixer/ghost_fixer_cubit.dart
Fixes an issue where the bloc wouldn't stop emitting states.
> PE 919 fix ghost fixer

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/drive_detail/drive_detail_state.dart
- lib/blocs/drive_detail/selected_item.dart
- lib/blocs/fs_entry_activity/fs_entry_activity_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
- lib/blocs/fs_entry_move/fs_entry_move_cubit.dart
- lib/blocs/ghost_fixer/ghost_fixer_cubit.dart
- lib/components/app_drawer/app_drawer.dart
- lib/components/fs_entry_move_form.dart
- lib/components/ghost_fixer_form.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/daos/drive_dao/folder_with_contents.dart
- lib/pages/app_router_delegate.dart
- lib/pages/drive_detail/components/drive_detail_actions_row.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- lib/pages/drive_detail/components/drive_detail_data_table.dart
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
- lib/pages/drive_detail/drive_detail_page.dart
- test/models/daos/drive_dao_test.dart
Adds a SelectedItem class to improve readability and avoid use of booleans.
> refactor: improve selected item readability

- lib/pages/drive_detail/components/custom_paginated_data_table.dart
Fixes issue where an empty page was shown at certain page counts.
> PE 975/Fix wrong last page

- pubspec.yaml
- web/index.html
> chore: version up to 1.6.0

- pubspec.yaml
- web/index.html
Up app version to 1.6.1 and index.html version to 52
> chore: version up to 1.6.1

- lib/blocs/drive_detail/drive_detail_cubit.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
Updates arweave-dart to handle uncaught errors in the upload chunk post request.
> PE-1008 : refactor/handle unknown upload errors

- pubspec.lock
- pubspec.yaml
- web/index.html
Also updates arweave-dart ref to tag v.2.0.1.
> chore: version up to 1.7.2 PE-1026

- pubspec.lock
- pubspec.yaml
Corrects type in arweave-dart version tag
> fix: correct arweave-dart tag PE-1026

- lib/blocs/sync/sync_cubit.dart
Stops the app from starting a sync if the sync state in SyncInProgress
> fix/don't sync if sync in progress PE-1002

- pubspec.yaml
- web/index.html
> chore: version up to 1.7.3 PE-1072

- lib/blocs/upload/bundle_upload_handle.dart
- lib/blocs/upload/file_upload_handle.dart
- lib/blocs/upload/upload_cubit.dart
- pubspec.lock
- pubspec.yaml
Improve file upload speeds by parallelising the seeding of transaction chunks.
> feat: improve file upload speeds PE-1056

- lib/blocs/upload/upload_cubit.dart
- pubspec.lock
- pubspec.yaml
Adds logs to upload function for diagnostics.
> chore: add logging for chunk uploads

- lib/blocs/drive_detail/drive_detail_state.dart
- lib/blocs/upload/upload_cubit.dart
- lib/pages/drive_detail/components/drive_detail_data_table.dart
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
- pubspec.lock
- pubspec.yaml
- web/index.html
Integration branch of UI fixes for easier testing.
Contains:
PE-1084
PE-1093
PE-905
PE-1100
> integration branch for ui fixes

- pubspec.lock
- pubspec.yaml
Updates the app version and arweave-dart.
> chore: update pubspec PE-1103

- pubspec.yaml
- web/index.html
> chore: bump dev version PE-1103

- web/index.html
> chore: up index.html version PE-1113

- lib/components/drive_share_dialog.dart
- lib/components/upload_form.dart
- lib/models/file_entry.dart
- pubspec.yaml
- web/index.html
- Add scroll to large list of conflicting files.
I just changed this file: _lib/components/upload_form.dart_, the others is due to the dev merge.
> Pe 1128 add scrolling to conflicts dialog

- lib/components/create_manifest_form.dart
- lib/components/drive_attach_form.dart
- lib/components/drive_create_form.dart
- lib/components/drive_rename_form.dart
- lib/components/folder_create_form.dart
- lib/components/fs_entry_rename_form.dart
- lib/components/ghost_fixer_form.dart
- lib/components/upload_form.dart
- lib/l10n/app_en.arb
- lib/l11n/validation_messages.dart
- lib/pages/profile_auth/components/profile_auth_add_screen.dart
- lib/pages/profile_auth/components/profile_auth_onboarding_screen.dart
- lib/pages/profile_auth/components/profile_auth_unlock_screen.dart
This PR takes the newly introduced strings from [PE-1105](https://github.com/ardriveapp/ardrive-web/pull/401) (child of PE-815), [PE-1003](https://github.com/ardriveapp/ardrive-web/pull/385) and [PE-1121](https://github.com/ardriveapp/ardrive-web/pull/407) to apply to them internationalization
> PE-1137: Localize newly added strings

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/file_download/file_download_cubit.dart
- lib/blocs/file_download/personal_file_download_cubit.dart
- lib/components/file_download_dialog.dart
- lib/entities/string_types.dart
- lib/pages/drive_detail/components/drive_detail_actions_row.dart
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
- lib/pages/drive_detail/drive_detail_page.dart
- web/index.html
Adds a download link to the specific versions in the activity sidebar.
> feat: add download link to versions PE-1135

- pubspec.yaml
> chore: bump version to 1.13.0

- lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
Passes the new name to the folder/file name conflict check function.
> PE 1238/Fix broken rename

- lib/blocs/folder_create/folder_create_cubit.dart
- lib/blocs/fs_entry_move/fs_entry_move_cubit.dart
- lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- lib/l10n/app_en.arb
- lib/models/daos/drive_dao/drive_dao.dart
- test/blocs/upload_cubit_test.dart
Checks for file and folder name conflicts on folder creation and file uploads.
> PE 618/Dont allow files and folders with the same name

- lib/blocs/sync/sync_cubit.dart
- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/DriveEntityHistory.graphql
- Change the function _syncDrive from recursive to iterative
- Paginate the process after getting the transactions with pages of 200 entities per time
> PE-1342 Change the _syncDrive function from recursive to iterative

- lib/utils/upload_plan_utils.dart
Adds missing driveKey to FolderUploadHandle.
> fix: fix missing cipher on private folder upload PE-1398

- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/upload/cost_estimate.dart
- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_handles/bundle_upload_handle.dart
- lib/blocs/upload/upload_handles/file_v2_upload_handle.dart
- lib/services/pst/pst.dart
This PR adds the community tip to v2 data transactions and consolidates handling the community tip to the `PstService` class.
> feat(tips on v2): Add community tip directly to v2 data transaction PE-1453

- pubspec.lock
- pubspec.yaml
Update arweave-dart version to 3.2.0
> chore(arweave-dart) Update arweave-dart version to 3.2.0

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
Pending `es` translations for PE-906
> feat(localization es): attach drives on wallets with no drives PE-1499

- lib/blocs/upload/enums/conflicting_files_actions.dart
- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- test/blocs/upload_cubit_test.dart
Skip files above limit and upload remaining ones.
> Fix: Skip files above limit and upload remaining ones.

- lib/components/drive_detach_dialog.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
Fixes the English translations as well. And adds the detachEmphasized key to the ARB file.
> PE-1602: adds translations for the Detach Drive feat

- README.md
- lefthook.yml
- lefthook/version_checker.sh
- pubspec.yaml
- Add Flutter version to pubspec.yaml
- Check if you're running the same Flutter version before commit
You need to run `lefthook install` again to sync the new checker
> feat(lefthook): check if local flutter version is right

- lib/blocs/feedback_survey/feedback_survey_cubit.dart
- lib/blocs/feedback_survey/feedback_survey_state.dart
- lib/blocs/sync/sync_cubit.dart
- lib/components/create_manifest_form.dart
- lib/components/drive_share_dialog.dart
- lib/components/feedback_survey.dart
- lib/components/file_share_dialog.dart
- lib/components/upload_form.dart
- lib/pages/app_router_delegate.dart
- test/blocs/feedback_survey_cubit_test.dart
The modal has to appear no more than once per session.
The events that will trigger the modal to open will be only:
- Upload folder
- Upload file
- Manifest Creation
- Sharing drive/file
> PE-1663: Feedback Modal triggers

- lib/blocs/upload/enums/conflicting_files_actions.dart
- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
- lib/pages/drive_detail/components/drive_file_drop_zone.dart
- test/blocs/upload_cubit_test.dart
Changes the order of validation from:
**name conflicting → check file size** 
to
**check file size → name conflicting**
> feat: check for files above limit first and then check for conflicts

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/models/daos/drive_dao/drive_dao.dart
- pubspec.lock
Adds natural sorting only when sorting by name in explorer.
> feat: implement natural sort in drive table PE-1642

- lib/l10n/app_zh.arb
Co-authored-by: Suning Yao <sy2940@nyu.edu>
> feat(locale zh): adds missing translations PE-1463

- lib/pages/congestion_warning_wrapper.dart
- lib/services/arweave/arweave_service.dart
Removes cached mempool stream.
> refactor: remove mempool stream PE-1579

- lib/components/drive_share_dialog.dart
- lib/components/profile_overlay.dart
Changes:
- Use different style rules to align the button to the left
- Align the button when not logged in as well
- Make the Leave Feedback button to be underlined and bold. Also add a blank space above.
- Show modal after Drive Share Dialog is dismissed (same behavior than File Share Dialog)
> PE-1580: Various fixes

- pubspec.yaml
> chore: version up to 1.23

- pubspec.yaml
> chore(bump version) bump version to 1.27.0

- lib/models/daos/drive_dao/drive_dao.dart
- lib/utils/compare_alphabetically_and_natural.dart
- test/utils/compare_alphabetically_and_natural_test.dart
Today our sort gives preference to file names with upper case. See that TEST FILEs are above the download_progress... file.
We are setting to lower case all names on files and folder before doing the comparison.
> fix(sort alphabetically) sorts alphabetically regardless of if something is capitalized or not

- ardrive_io/lib/src/web/web_io.dart
Use `cross_file` package to save files on Web.
> fix(web io save files) use previous implementation saving files on web

- lib/blocs/upload/upload_cubit.dart
> fix: correct public file size limit PE-2123

- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/Runner/Info.plist
- Update Podfile with the supported iOS version
- Apply settings upgrade from XCode (especially related to an older iOS version, update packages, and fix deprecates)
- Use the correct app name
- Use the correct bundle ID
- Add permissions
- Define device screen orientation
> chore(iOS configs) configure iOS app PE-2065

- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/example/drive/MainActivity.kt
- android/app/src/profile/AndroidManifest.xml
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- Use the correct package name
- Use the correct app name
- Add permissions
- Define device screen orientation
- Update build.gradle:
- Add supported sdk versions 
- add correct application id io.ardrive.app
> chore(android settings) configure Android app

- test/blocs/data_export_cubit_test.dart
- test/blocs/upload_cubit_test.dart
- test/test_utils/fake_data.dart
> tests(blocks): fix upload and data export cubit tests

- pubspec.yaml
bump version.
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/03okn1u68vjf0
> chore: bump version

- .vscode/launch.json
- lib/components/upload_form.dart
When you click on upload file button it will show file picker on web and display multiple options (gallery, file picker and camera) on mobile
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/71sc6r63e01rg
> PE-2322: show file source options just for mobile

- lib/components/plus_button.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/pages/no_drives/no_drives_page.dart
Changelog
- Adds the Plus Button to the NoDrives view
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/506v4nbvevm8o
> PE-2340: feat(plus button): adds the plus button for the NoDrives view

- ardrive_io/lib/src/ardrive_downloader.dart
- lib/blocs/file_download/file_download_cubit.dart
- lib/blocs/file_download/personal_file_download_cubit.dart
- lib/blocs/upload/upload_handles/file_data_item_upload_handle.dart
- pubspec.lock
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4dfliaplq13s0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/50a7em800d6d0
> PE-2386: fix download files on web

- lib/pages/shared_file/shared_file_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3c30u6t1lk94g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/49nmeimdd4aro
> PE-2231: download files when in landscape

- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6vsp2nb5c9q8g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1h55b74i6ai18
> bump version for next version

- ios/Podfile
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4me0kr6volmsg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0eij3seqoiocg
> fix xcode ask for certs

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_handles/bundle_upload_handle.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1ns91i56h6vf8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6j7jelopf2250
> PE-2410: folder and multiple files and cannot be uploaded using ar connect

- lib/app_shell.dart
- lib/components/profile_overlay.dart
- lib/pages/profile_auth/components/profile_auth_add_screen.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0l94bllt3ql08
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0c03jl65j3jt0
> PE-2360: feat: add Biometric on/off toggle to the Profile section

- lib/l10n/app_en.arb
- lib/pages/profile_auth/components/profile_auth_add_screen.dart
- lib/pages/profile_auth/components/profile_auth_shell.dart
- lib/pages/profile_auth/components/profile_auth_unlock_screen.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ajint90i62b0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4p26m7414nj8g
> PE-2361: Improve login screen

- lib/blocs/upload/upload_handles/file_v2_upload_handle.dart
- lib/entities/constants.dart
- lib/entities/entity.dart
- lib/services/arweave/arweave_service.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6jrmui366cu8g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/22cg081vkk5ro
> PE-2466: feat: add bar tags

- .github/workflows/pr.yaml
- .github/workflows/production.yaml
- .github/workflows/staging.yaml
- lib/components/app_dialog.dart
- pubspec.yaml
Before:
After:
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3vghdjhgb309g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7cijb554fscio
> PE-2475: fix dialog radius and action button paddings

- android/fastlane/Fastfile
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/15d6hjmlmc3do
> fix aab path when having flavors

- lib/pages/profile_auth/components/profile_auth_add_screen.dart
- lib/pages/profile_auth/components/profile_auth_onboarding_screen.dart
- lib/pages/profile_auth/components/profile_auth_prompt_wallet_screen.dart
- lib/pages/profile_auth/components/profile_auth_shell.dart
- lib/pages/profile_auth/components/profile_auth_unlock_screen.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6t4f0idcrqcig
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6g794tsetav3g
> PE-2524: align login screen at the middle of the screen

- lib/misc/resources.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6u966fhic6c48
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/14jlh77bpsnu8
> PE-2513: change help link and survey button link

- android/fastlane/metadata/android/en-US/video.txt
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6shbqjd36arbo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4c3qchn7qrg7o
> chore(android): remove youtube video from release

- lib/components/copy_icon_button.dart
- lib/components/profile_overlay.dart
- lib/l10n/app_en.arb
- lib/pages/drive_detail/components/fs_entry_side_sheet.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/pages/shared_file/shared_file_side_sheet/shared_file_side_sheet.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5ffhgikbj9818
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0hnh0qu2friko
> PE-2362: Add copy wallet address button

- android/fastlane/metadata/android/en-US/changelogs/12.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/573e77rkl7ri8
> bump version and add change log

- localizely.yaml
**Changes**
- Adds the YAML configuration for the Integration with Localizely
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/43ipoo0fel860
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/193g6deo29bno
> PE-2581: Localizely Integration

- localizely.yml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/43j3ecf2o7bc8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/3lpi3vs96hquo
> feat(localizely): use the correct localizely branch PE-2581

- lib/components/file_download_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7toenm0snneo0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2rqtdl1sonf00
> PE-2608: cancel button doesnt work for downloading files

- packages/ardrive_ui_library/.vscode/settings.json
- packages/ardrive_ui_library/lib/src/components/toggle.dart
- packages/ardrive_ui_library/storybook/lib/src/ardrive_app_base.dart
- packages/ardrive_ui_library/storybook/lib/src/button.dart
- packages/ardrive_ui_library/storybook/lib/src/card.dart
- packages/ardrive_ui_library/storybook/lib/src/colors.dart
- packages/ardrive_ui_library/storybook/lib/src/shadows.dart
- packages/ardrive_ui_library/storybook/lib/src/story_book.dart
- packages/ardrive_ui_library/storybook/lib/src/text_field.dart
- packages/ardrive_ui_library/storybook/lib/src/toggle.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5c8k7gjjlbev8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/39cuj1gbfjego
> PE-2655 use knobs to change component properties themes and styles

- packages/ardrive_ui_library/lib/src/components.dart
- packages/ardrive_ui_library/lib/src/components/toggle.dart
- packages/ardrive_ui_library/lib/src/components/toggle_switch.dart
- packages/ardrive_ui_library/storybook/lib/src/toggle.dart
To see examples of the component, go to the storybook and `Toggle` section.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6bob81d2b69s0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2fr32e4q4ks0o
> PE-2566: implement the toggle switch component

- lib/components/create_manifest_form.dart
- lib/misc/resources.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1h0gb9n0f2vk8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7trp4h7u6pdog
> PE-2698: fix(manifest link) update link and add a space

- packages/ardrive_ui_library/lib/src/components.dart
- packages/ardrive_ui_library/lib/src/components/progress_bar.dart
- packages/ardrive_ui_library/lib/src/styles/colors/sematic_colors.dart
- packages/ardrive_ui_library/pubspec.yaml
- packages/ardrive_ui_library/storybook/lib/src/progress_bar.dart
- packages/ardrive_ui_library/storybook/lib/src/story_book.dart
- packages/ardrive_ui_library/storybook/pubspec.lock
- packages/ardrive_ui_library/test/src/components/progress_bar_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3coci7lcb3kl8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6f1tvbv35qktg
> PE-2562: progress bar component

- lib/l10n/app_en.arb
> feat(localization): fixes typos in the ARB keys

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7v030gf5rlhn8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0htgn55nhgmho
> PE-2784: fix storage permissions for android 13

- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/72eh5rvtmo5jo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/3avb5tvsrml10
> feat(version): after-release version bump PE-2795

- lib/main.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- web/ardrive-http.js
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ht5b1f3cgetg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/203hbf02mmmj0
> PE-2823: set 8s network calls timeout and change contract reader order

- lib/entities/constants.dart
- lib/entities/snapshot_entity.dart
- test/entities/snapshot_entity_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/52rl6dn1458j0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/3rv1tqj0m2sqg
> PE-2824: feat(snapshot entity): declares SnapshotEntity

- android/fastlane/metadata/android/en-US/changelogs/17.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5s8ne2kdb2u60
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5h8j8kife0lmg
> chore: update version to 1.41.2

- android/fastlane/metadata/android/en-US/changelogs/18.txt
- lib/models/tables/all.drift
Commit at prod: d6d0ceba
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6r7achemkoai8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2pngogrl03hg0
> [DO NOT MERGE]: Test production 2

- pubspec.lock
- pubspec.yaml
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/25nspupbvk7s8
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6tthg25hk89ro
> PE-2920: fixes get last modified date in firefox

- assets/config/prod.json
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5au43eo8hp3j8
> feat: disable useTurbo feature flag

- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/create_snapshot/create_snapshot_state.dart
- lib/components/create_snapshot_dialog.dart
- lib/components/new_button.dart
- lib/l10n/app_en.arb
- lib/services/arweave/arweave_service.dart
- lib/services/config/app_config.dart
- lib/services/config/config_service.dart
- lib/utils/snapshots/snapshot_item_to_be_created.dart
WIP
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3i8m7597kbni0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0cb0ilob1rgs8
> PE-2815: implements the UI for creating snapshots

- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/components/app_dialog.dart
- lib/components/create_snapshot_dialog.dart
- lib/components/feedback_survey.dart
- lib/components/progress_dialog.dart
- lib/components/title_with_close_action.dart
- test/blocs/create_snapshot_cubit_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/11t1bdhsbckho
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2aiq8t9tiad50
> PE-2930: Let the "Computing snapshot" modal to be cancellable

- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/create_snapshot/create_snapshot_state.dart
- lib/components/create_snapshot_dialog.dart
- lib/l10n/app_en.arb
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/22np02cvd5vpo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0dlt39ef468cg
> PE-2931: Explanation modal

- lib/components/create_snapshot_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0qp06oe406lpo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2abm9lsk70mqo
> PE-2956: removes "This might take a while..." when uploading

- lib/components/create_snapshot_dialog.dart
- lib/l10n/app_en.arb
- Adds "Try again" on the failure modal
- Replaces quotes with a Strong text
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5rcieb8o0ei6o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7oduoicffo1bo
> PE-2957: Adds Try Again button on failure

- docs/ArweaveFS.md
- lib/entities/entity.dart
- lib/services/arweave/graphql/queries/AllFileEntitiesWithId.graphql
- lib/services/arweave/graphql/queries/DriveEntityHistory.graphql
- lib/services/arweave/graphql/queries/FirstDriveEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/FirstFileEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/LatestDriveEntityWithId.graphql
- lib/services/arweave/graphql/queries/LatestFileEntityWithId.graphql
- lib/services/arweave/graphql/queries/UserDriveEntities.graphql
- lib/utils/bundles/fake_tags.dart
- test/entities/snapshot_entity_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/70tqafg6v1ivg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/3qdfhnns8oq9o
> PE-2963: Bump ArFS version

- android/fastlane/metadata/android/en-US/changelogs/22.txt
- pubspec.lock
- pubspec.yaml
- Fixes an issue downloading files that take more than 8 seconds to complete
> Release v1.42.1

- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/create_snapshot/create_snapshot_state.dart
- lib/blocs/sync/sync_cubit.dart
- lib/entities/snapshot_entity.dart
- lib/utils/html/html_util.dart
- lib/utils/html/implementations/html_stub.dart
- lib/utils/html/implementations/html_web.dart
- lib/utils/snapshots/snapshot_item_to_be_created.dart
- test/blocs/create_snapshot_cubit_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4ovmu33dens1o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6acsnett6b2ao
> PE-3012: Resume prepare/sign on tab focus when ArConnect wallet

- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/sync/sync_cubit.dart
- lib/components/create_snapshot_dialog.dart
- lib/pages/app_router_delegate.dart
- lib/utils/html/html_util.dart
- test/blocs/create_snapshot_cubit_test.dart
- test/test_utils/mocks.dart
- test/utils/html_utils/tab_visibility_singleton_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7a321udf9qsjg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6jtrihk3celt8
> PE-3048: unit test retry prepare/sign snapshot tx on tab focus when ArConnect

- .github/workflows/pr.yaml
- .github/workflows/production.yaml
- .github/workflows/staging.yaml
- android/fastlane/metadata/android/en-US/changelogs/23.txt
- firebase.json
- pubspec.yaml
Release notes
- Invalidate Firebase cache for feature flag config files
> PE-3094: Release v1.43.1

- lib/authentication/login/views/login_page.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0c1cvti6bg0a8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4e9jieqhhg8q8
> PE-3130: add click cursor when hovering T&C

- lib/authentication/login/views/login_page.dart
- pubspec.lock
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0feb3kr1q2a2g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5krls3017tli8
> PE-3134: keep state when resizing login page

- lib/pages/drive_detail/components/drive_detail_breadcrumb_row.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- lib/pages/drive_detail/drive_detail_page.dart
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5v8l54k67nhto
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7hdlokq8h7isg
> PE-3126: implement breadcrumb

- lib/pages/drive_detail/components/drive_detail_data_list.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2cq84v0o1rl68
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/39s2rrg6q2hh0
> PE-3127: implement sorting with new data table

- android/fastlane/metadata/android/en-US/changelogs/27.txt
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1vtam04fv9ovo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6gs0v9isgc9co
> feat(release): android release notes PE-3149

- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4bpq0rl6n0r5g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/76lmqj1ilg8n0
> feat(version): before-release version bump PE-3149

- lib/authentication/login/views/login_page.dart
- pubspec.lock
- pubspec.yaml
- test/authentication/login/blocs/login_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5omam1qf5d4qg
> PE-3145: issues when using a new wallet with ar connect

- localizely.yml
Lets localizely to export the new Hindi language as well
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0glngnmqhf59g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0dg9nscab3mb8
> PE-3171: Adds the Hindi (hi) language in the download list 

- lib/main.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/06t6hjjjmeba8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2d0s39ksk5h40
> PE-3171: Enable Hindi lang

- lib/blocs/drive_rename/drive_rename_cubit.dart
- lib/blocs/drive_rename/drive_rename_state.dart
- lib/components/drive_rename_form.dart
- lib/components/drive_share_dialog.dart
- lib/components/file_share_dialog.dart
- lib/components/folder_create_form.dart
- lib/components/fs_entry_rename_form.dart
- lib/pages/drive_detail/components/drive_detail_actions_row.dart
- lib/pages/drive_detail/components/drive_detail_breadcrumb_row.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/utils/validate_folder_name.dart
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6sv46pvdl9i5g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7mfhrkmtr670o
> PE-3177: implement drive options

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3v4upan23lhjg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/251o2lflts0hg
> PE-3196: add hover effect at the number of pages indicator and improve the visibility when hovering a dropdown item 

- pubspec.lock
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0r10euitr8hno
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2mcn96v2me19g
> feat(deppendencies): updates bad dependency

- lib/blocs/sync/utils/sync_drive.dart
- lib/services/arweave/arweave_service.dart
- lib/utils/snapshots/drive_history_composite.dart
- lib/utils/snapshots/height_range.dart
- lib/utils/snapshots/snapshot_item.dart
The relevant changes are at `lib/services/arweave/arweave_service.dart`
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/10237vmu9hjno
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/147bb0eijq3j0
> PE-3191: don't request data of snapshot at metadata sync time

- localizely.yml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/44sg6c3uear6o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5sfqa05fkuh0g
> feat(localizely config): updates the export rules PE-3171

- ios/Podfile.lock
- lib/app_shell.dart
- lib/components/app_bottom_bar.dart
- lib/components/fs_entry_move_form.dart
- lib/components/new_button/new_button.dart
- lib/components/profile_card.dart
- lib/pages/drive_detail/components/drive_detail_folder_empty_card.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- lib/pages/drive_detail/components/drive_explorer_mobile_view.dart
- lib/pages/drive_detail/components/dropdown_item.dart
- lib/pages/drive_detail/drive_detail_page.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7cbqb0qpgdp4o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/75884m0b7mnv8
> PE-3309: new drive explorer mobile

- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3ul6ja6gmces0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4vlt2jbv9r790
> chore(version): before-release version bump PE-3399

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- lib/components/fs_entry_move_form.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7222lb2keobu8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/42efa472rb4l8
> PE-3358: when a folder is selected to be moved into a folder that has just been created the folder is not moved to the selected destination

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7b3g57omj9g40
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/61ac5ckj50c18
> PE-3374: when multiselect list is static we cant continue selecting items without pressing command key

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4uogchrqqa2eg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2s11iglqmdr3o
> PE-3357: checkbox list is hidden if we want to uncheck a file folder after selecting all of them

- lib/components/side_bar.dart
- lib/components/theme_switcher.dart
- lib/l10n/app_en.arb
- lib/main.dart
- lib/pages/app_router_delegate.dart
- lib/theme/theme.dart
- lib/theme/theme_switcher_bloc.dart
- lib/theme/theme_switcher_event.dart
- lib/theme/theme_switcher_state.dart
- lib/user/repositories/user_preferences_repository.dart
- lib/user/user_preferences.dart
- pubspec.lock
- test/theme/theme_switcher_bloc_test.dart
- test/user/repositories/user_preferences_repository_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5aa65p3f6ustg
> PE-3044: new side bar with theme persistence

- lib/pages/drive_detail/components/drive_detail_data_list.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/45p4d76pln0kg
> PE-3374: multiselect by pages

- lib/components/fs_entry_move_form.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7e1ls4jfld0j8
> PE-3424: move button not visible on screen with 480 x 800 resolution

- lib/components/new_button/new_button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1q5uhdscfko7g
> PE-3434: plus button shows a design error when the menu options are displayed at 480 x 800 resolution

- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- lib/utils/constants.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/12pi04m0rgu8g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/05h6rgriosgu0
> PE-3441: the preview image is zoomed

- android/fastlane/metadata/android/en-US/changelogs/34.txt
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/387jns3vhmtgg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7l4s3ptlgnbd0
> chore(android release notes): corrects the notes PE-3476

- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/blocs/shared_file/shared_file_cubit.dart
- lib/blocs/shared_file/shared_file_state.dart
- lib/components/details_panel.dart
- lib/pages/app_router_delegate.dart
- lib/pages/shared_file/shared_file_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/54ntpq1be94b0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/3dehv0lu9r138
> PE-3449: enable private files preview on share page

- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/components/file_download_dialog.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- lib/utils/constants.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1qaqmj1bvh3i8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/28vnd4rh816g0
> PE-3217: fixes on video player

- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/upload/cost_estimate.dart
- lib/components/create_snapshot_dialog.dart
- lib/services/arweave/arweave_service.dart
- lib/utils/ar_cost_to_usd.dart
- test/blocs/create_snapshot_cubit_test.dart
- test/blocs/upload_cubit_test.dart
- test/services/arweave/arweave_service_test.dart
- test/uploads/cost_estimate_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ne52vr797q7g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0v8591egvipd0
> PE-3517: Do not fail upload when USD price is unavailable - SNAPSHOT CREATION

- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/create_manifest/create_manifest_state.dart
- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/upload/cost_estimate.dart
- lib/blocs/upload/upload_cubit.dart
- lib/components/create_manifest_form.dart
- lib/components/create_snapshot_dialog.dart
- lib/components/upload_form.dart
- lib/l10n/app_en.arb
- lib/services/arweave/arweave_service.dart
- lib/utils/ar_cost_to_usd.dart
- test/blocs/create_snapshot_cubit_test.dart
- test/blocs/upload_cubit_test.dart
- test/services/arweave/arweave_service_test.dart
- test/uploads/cost_estimate_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1ili51vmjhlko
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/14106k3v1uat0
> PE-3517: Do not fail upload when USD price is unavailable

- lib/blocs/sync/utils/sync_drive.dart
- lib/services/arweave/arweave_service.dart
- lib/utils/snapshots/snapshot_item.dart
- test/utils/drive_history_composite_test.dart
- test/utils/snapshot_drive_history_test.dart
- test/utils/snapshot_item_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5fu46ovqnj81g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0mvg6hsnuavro
> PE-2786: Utilize sandboxed url for Quick Sync

- lib/pages/drive_detail/components/drive_detail_breadcrumb_row.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ehh6jedp8c2o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7g1ejtf8frafo
> PE-3578: update breadcrumb UI

- lib/pages/shared_file/shared_file_page.dart
- pubspec.lock
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/198dphf7jf948
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/237tg783qm94o
> PE-3536: fix font package

- lib/authentication/login/blocs/login_bloc.dart
- lib/misc/resources.dart
- pubspec.lock
- test/authentication/login/blocs/login_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4fbo3s2988fgo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/57t1gpvoe5200
> PE-3570 update onboarding

- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/create_snapshot/create_snapshot_state.dart
- lib/blocs/drive_create/drive_create_cubit.dart
- lib/blocs/drive_rename/drive_rename_cubit.dart
- lib/blocs/folder_create/folder_create_cubit.dart
- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
- lib/blocs/ghost_fixer/ghost_fixer_cubit.dart
- lib/blocs/sync/utils/add_drive_entity_revisions.dart
- lib/blocs/sync/utils/add_file_entity_revisions.dart
- lib/blocs/sync/utils/add_folder_entity_revisions.dart
- lib/blocs/upload/upload_handles/file_data_item_upload_handle.dart
- lib/blocs/upload/upload_handles/file_v2_upload_handle.dart
- lib/blocs/upload/upload_handles/folder_data_item_upload_handle.dart
- lib/components/create_snapshot_dialog.dart
- lib/entities/drive_entity.dart
- lib/entities/file_entity.dart
- lib/entities/folder_entity.dart
- lib/l10n/app_en.arb
- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/drive_revision.dart
- lib/models/file_revision.dart
- lib/models/folder_revision.dart
- lib/models/queries/drive_queries.drift
- lib/services/arweave/arweave_service.dart
- test/blocs/create_snapshot_cubit_test.dart
- test/models/daos/drive_dao_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/38jut0c555lo0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/77k7cqpmpun00
> PE-3582: Add extra step before Snapshot Creation: fetch non-synced custom metadata

- .github/workflows/production.yaml
- .github/workflows/staging.yaml
- firebase.json
- pubspec.yaml
- web/index.html
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4q8893m9d7apo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0n8qt1mir2vn8
> pre release setup

- android/fastlane/metadata/android/en-US/changelogs/40.txt
- pubspec.lock
- pubspec.yaml
- Refreshed user interface
- Dark mode
- Share page now includes image previews
- Drag n' drop multiple files
- View transaction on ViewBlock from Details Panel
- New sidebar
- Easier file multiselect
- Usernames no longer needed for login
> PE-3744: Release v2.0.0

- android/fastlane/metadata/android/en-US/changelogs/41.txt
- pubspec.yaml
Changes
- App version bump
- Android release notes (41.txt)
> PE-3774: Before-release preparations

- android/fastlane/metadata/android/en-US/changelogs/42.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2jum26r7a5at8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2kmqabk88s3bo
> PE-3783: before-release preparations

- lib/components/progress_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2k1ahlib6c5e0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0u2pmd7mqd4b8
> PE-3791: Adds back the CANCEL button to Snapshot Creation

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/623cufrg1gfto
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/44s9kvtgr4mf0
> PE-3924: fix(datatable): use fixed version of datatable for issue with sort

- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3cvhlcd986k50
> PE-3934: modal does not close after successful or failed file download on mobile

- lib/components/top_up_dialog.dart
- lib/components/turbo_balance_widget.dart
- lib/turbo/topup/blocs/topup_estimation_bloc.dart
- lib/turbo/topup/components/turbo_topup_scaffold.dart
- lib/turbo/utils/utils.dart
- lib/utils/winston_to_ar.dart
- pubspec.lock
- test/turbo/blocs/topup_estimation_bloc_test.dart
- test/turbo/utils/utils_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2qplrgcj5dprg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1tv7lsg7e8qp0
> PE-3990: (fine tune): fix sizes and fonts for the estimation view

- lib/services/turbo/payment_service.dart
- lib/turbo/topup/blocs/topup_estimation_bloc.dart
- lib/turbo/topup/blocs/topup_estimation_event.dart
- lib/turbo/topup/models/payment_model.dart
- lib/turbo/topup/models/price_estimate.dart
- lib/turbo/topup/views/turbo_modal.dart
- lib/turbo/turbo.dart
- test/turbo/turbo_test.dart
…plement a listener to update when quote should be updated
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7eq6f17alj5kg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6u1q1m0tg6j10
> PE-3991: update quote every 5 minutes

- lib/main.dart
- lib/turbo/topup/views/turbo_modal.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3i3ck6hvu9j30
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/3mnk5g7iedu1g
> PE-4012: initialize stripe only on the topup modal

- assets/config/dev.json
- assets/config/prod.json
- lib/dev_tools/app_dev_tools.dart
- lib/services/config/app_config.dart
- lib/turbo/topup/views/topup_modal.dart
- lib/turbo/turbo.dart
- pubspec.lock
- test/services/config/config_fetcher_test.dart
- test/services/config/config_service_test.dart
- test/turbo/turbo_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/29jkaokk4q2n0
> PE-4020: add stripe publishable key to the env config variable

- lib/components/top_up_dialog.dart
- lib/turbo/topup/blocs/topup_estimation_bloc.dart
- lib/turbo/topup/blocs/topup_estimation_state.dart
- lib/turbo/topup/blocs/turbo_topup_flow_state.dart
- lib/turbo/topup/views/topup_modal.dart
- lib/turbo/topup/views/topup_review_view.dart
- lib/turbo/topup/views/turbo_error_view.dart
- pubspec.lock
- test/turbo/blocs/topup_estimation_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3fqtb9g8padeg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/69nvasedepuug
> PE-4019: handle error opening the turbo modal

- lib/turbo/topup/blocs/payment_review/payment_review_bloc.dart
- lib/turbo/topup/blocs/turbo_topup_flow_bloc.dart
- lib/turbo/topup/blocs/turbo_topup_flow_state.dart
- lib/turbo/topup/views/topup_modal.dart
- lib/turbo/turbo.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0oft6n6491nd8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2hkuvm6341ndg
> PE-4023: credit card modal locked ond prod env

- lib/turbo/topup/blocs/payment_form/payment_form_bloc.dart
- lib/turbo/topup/blocs/payment_form/payment_form_state.dart
- lib/turbo/topup/blocs/payment_review/payment_review_bloc.dart
- lib/turbo/topup/blocs/payment_review/payment_review_event.dart
- lib/turbo/topup/views/topup_payment_form.dart
- lib/turbo/topup/views/topup_review_view.dart
- test/turbo/blocs/payment_form/payment_form_bloc_test.dart
- test/turbo/blocs/payment_review/payment_review_bloc_test.dart
- test/turbo/blocs/topup_estimation_bloc_test.dart
- test/turbo/turbo_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/40o2c6pgfek8o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5mmg0ncffu6fg
> PE-4026: handle error updating the quote on payment form

- lib/services/turbo/payment_service.dart
- lib/turbo/topup/views/topup_review_view.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/69e079h4bsahg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5a3d9a27ipg2o
> PE-4035: feat(email validation): disable button when email is invalid

- lib/services/turbo/payment_service.dart
- lib/utils/turbo_utils.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5ivuc005j8sjo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1pn9v3miudl10
> PE-4061: unable to reach review screen when connected via ar connect

- android/fastlane/metadata/android/en-US/changelogs/48.txt
- pubspec.yaml
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/525irna4lif5o
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5hnmlg71ukv5o
> PE-4066: before-release preparations

- lib/components/upload_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7ugdr2ejs6fh0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/557pqdm53ntd8
> PE-4088: update insufficient balance errors

- lib/blocs/upload/models/upload_plan.dart
- lib/core/upload/uploader.dart
- test/core/upload/uploader_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0vt7bqlukssho
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0r1nh30c7abgo
> PE-4096: does not conform to requiriment of uploading up to 500000 bytes free

- android/fastlane/metadata/android/en-US/changelogs/49.txt
- pubspec.yaml
- Update Zendesk/Help link
- Optimized the TransactionStatuses GQL query to only run for items not captured by snapshots, reducing unnecessary network requests and improving performance.
> PE-4123: Release 2.4.1

- lib/services/config/config_fetcher.dart
- test/services/config/config_fetcher_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5hrrs1h9h8ef8
> PE-4124: check issue with blank screen on staging

- android/app/build.gradle
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/staging.xcscheme
- ios/Runner/Info.plist
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4v3nv587tbv90
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/25cnoeeu4767o
> PE-4128: create staging env for ar drive app mobile

- lib/components/upload_form.dart
- lib/core/upload/uploader.dart
- test/core/upload/uploader_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2oim3mj393k2g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6ah4lg8nh8iio
> PE-4134: large file skipped but still uploaded and deducting ars

- lib/components/upload_form.dart
- lib/core/upload/uploader.dart
- lib/services/turbo/upload_service.dart
- lib/utils/data_item_utils.dart
- pubspec.lock
- pubspec.yaml
- test/core/upload/uploader_test.dart
- test/utils/data_item_utils_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6isbj6kjjc190
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/33g094sgln2dg
> PE-4143: feat(uploader): add progress indication

- lib/core/upload/uploader.dart
- test/core/upload/uploader_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5jm3uav8j0sg0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/78hl2m1jm9p4o
> allow free uploads even if the feature flag is off

- lib/blocs/sync/sync_cubit.dart
- lib/core/activity_tracker.dart
- lib/main.dart
- lib/pages/app_router_delegate.dart
- lib/turbo/topup/views/topup_modal.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7jvrjtlnaap48
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1emqn45sgg96o
> PE-4146: disable automatic sync when user is on the topup modal

- .github/workflows/pr.yaml
- lib/blocs/upload/upload_cubit.dart
- lib/core/upload/uploader.dart
- lib/services/turbo/upload_service.dart
- test/core/upload/uploader_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2po1g938v4tu0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/155lng3mvg9i8
> PE-4144: fix(uploader): send entity tx and data tx on filev2 uploader

- lib/services/turbo/upload_service.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5ee51cnss5v10
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7bpfpkupsmjgg
> PE-4164: fix wrong merge on upload

- lib/blocs/upload/upload_handles/file_v2_upload_handle.dart
- lib/entities/entity.dart
- lib/services/arweave/arweave_service.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/661l1iac623rg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1kiukal1o9dpo
> PE-4110: switch bAR for U

- lib/components/top_up_dialog.dart
- lib/l10n/app_en.arb
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4c0j5bftsj4to
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4ler4fr4mmu90
> PE-4155: design inconsistencies turbo top up

- lib/components/top_up_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/518j26q6aqku8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1k915h8jckam8
> PE-4187: Validation error doesn't render

- lib/core/upload/uploader.dart
- lib/services/turbo/upload_service.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/45god59vq2gmo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/49o2efbutk7c8
> PE-4185: unable to create folders with new button PE-4188

- lib/components/top_up_dialog.dart
- lib/cookie_policy_consent/blocs/cookie_policy_consent_bloc.dart
- lib/cookie_policy_consent/cookie_policy_consent.dart
- lib/cookie_policy_consent/views/cookie_policy_consent_modal.dart
- lib/l10n/app_en.arb
- test/cookie_policy_consent/blocs/cookie_policy_consent_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1filpmemcjl4g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/78ccn0knd14b8
> PE-4195: modal doesnt appear when logging in via ar connect

- lib/authentication/login/views/login_page.dart
- Cleaned up comments and added TODO's for localization
- Delayed pregeneration of wallet until after first frame after Create New Wallet initially renders
> Seed phrase login - Round 4

- lib/authentication/login/blocs/stub_web_wallet.dart
* run wallet generation in an Isolate to run off main thread on mobile
> Seed Phrase Login - Round 5

- lib/blocs/drives/drives_cubit.dart
- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/turbo/turbo.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/02q9kqp6ftorg
> chore: drift 2.0 migration

- lib/components/top_up_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4rrbq728j2ur0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0j7j7p47p3o1g
> PE-4194: spelling error in the modal

- lib/authentication/login/views/login_page.dart
- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/drive_detail/drive_detail_state.dart
- lib/l10n/app_en.arb
- lib/pages/drive_detail/drive_detail_page.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3b7k8n1q2cmto
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/56jsqbgnu1vbo
> add feedback to the user when folder is not found

- pubspec.lock
- pubspec.yaml
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4fd9jfrnua37g
> PE-4238: bump version for release

- assets/config/prod.json
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/445t3esg6b13o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/18aarq5qbmjro
> PE-4238: update prod.json

- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
- lib/core/upload/uploader.dart
- lib/turbo/topup/views/topup_modal.dart
- lib/turbo/turbo.dart
- Fixes the issue when the user opens the turbo topup modal while still on the upload modal
- Adds a timeout to wait for getting the balance (needs a better solution).
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2b2h458253pd0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/16aum5jg1fhco
> PE-4231: fix(turbo upload + payment)

- lib/authentication/login/views/login_page.dart
- lib/l10n/app_en.arb
- lib/misc/resources.dart
Removes the tooltip on the `howDoesKeyfileLoginWork` text
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7jl340r89j3p0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0lnbkgadmok60
> PE-4246: updates help text and link for login with keyfile and seed phrase

- lib/authentication/login/views/login_page.dart
- lib/l10n/app_en.arb
- lib/misc/resources.dart
- updates the onboarding and create password texts
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/37ligdae2g5qg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7j5m595cr2su0
> PE-4248: update new user flow texts

- lib/cookie_policy_consent/views/cookie_policy_consent_modal.dart
- lib/l10n/app_en.arb
- lib/misc/resources.dart
- adds to the cookie consent modal the learn more link pointing to the stripe article
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/46rv48n024jf0
> PE-4244: feat(cookie consent): Adds learn more link to the cookie consent modal

- lib/authentication/login/views/login_page.dart
Adds a small padding on top and bottom of the view
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/39pkif9h8abj0
> PE-4229: add padding on the getting state view

- lib/authentication/login/views/login_page.dart
https://github.com/ardriveapp/ardrive-web/assets/32248947/af0449eb-6589-410b-820f-12af344cce0a
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/14lpr1eaeqd8o
> PE-4297: add scroll bar to wallet creation on mobile view

- lib/authentication/login/views/login_page.dart
- lib/components/feedback_survey.dart
- lib/components/profile_card.dart
- lib/components/profile_overlay.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- lib/pages/drive_detail/components/hover_widget.dart
- lib/utils/open_url_utils.dart
- Adds the leave feedback button on the profile card
- implement a method to abstract the openUrl logic on the feedback survey URL
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4mh9grbvtscm0
> PE-4264: feat(leave feedback)

- lib/components/details_panel.dart
- lib/components/profile_card.dart
- lib/components/truncated_address.dart
- lib/l10n/app_en.arb
- lib/models/file_revision.dart
- lib/models/tables/file_entries.drift
- lib/models/tables/file_revisions.drift
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- lib/utils/truncate_string.dart
- test/utils/truncate_string_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2rh3k465asjmg
> PE-3986: Show original owner in Details Panel

- lib/components/details_panel.dart
- lib/core/arfs/entities/arfs_entities.dart
- lib/core/arfs/utils/arfs_factory.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6ovib16qopcio
> PE-3987: New activity interaction for pinned files

- lib/components/details_panel.dart
- lib/components/new_button/new_button.dart
- lib/components/pin_indicator.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/36es4okk50b80
> PE-3988: Adds new Pin icon

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_state.dart
- lib/components/details_panel.dart
- lib/entities/drive_entity.dart
- lib/entities/folder_entity.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2ji6dninudroo
> PE-4352: fix folders and drives

- lib/models/database/database.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6suc85uq06g0o
> PE-4352: adds the newly introduced columns

- lib/entities/drive_entity.dart
- lib/entities/entity.dart
- lib/entities/file_entity.dart
- lib/entities/folder_entity.dart
- lib/models/file_entry.dart
- lib/models/file_revision.dart
- lib/models/tables/drive_revisions.drift
- lib/models/tables/drives.drift
- lib/models/tables/file_entries.drift
- lib/models/tables/file_revisions.drift
- lib/models/tables/folder_entries.drift
- lib/models/tables/folder_revisions.drift
- test/entities/custom_json_metadata_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0qsd4cr8tocd0
> PE-4352: Track Custom JSON Metadata and Custom GQL Tags in the DB

- lib/models/daos/drive_dao/drive_dao.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/36uceccafl6i0
> PE-4393: properly track pinned data owner address

- lib/components/pin_file_dialog.dart
- lib/l10n/app_en.arb
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/15u5vb5q305d0
> PE-4310: Error feedback - Pins

- lib/entities/entity.dart
- lib/entities/file_entity.dart
- lib/services/arweave/graphql/queries/AllFileEntitiesWithId.graphql
- lib/services/arweave/graphql/queries/DriveEntityHistory.graphql
- lib/services/arweave/graphql/queries/FirstDriveEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/FirstFileEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/LatestDriveEntityWithId.graphql
- lib/services/arweave/graphql/queries/LatestFileEntityWithId.graphql
- lib/services/arweave/graphql/queries/UserDriveEntities.graphql
- test/entities/snapshot_entity_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0hu3sc5h3v3b8
> PE-3984: ArFS version bump

- lib/components/details_panel.dart
- lib/l10n/app_en.arb
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7cansgska3c30
> PE-4408: localizes 'File type' in the DETAILS section

- .github/workflows/pr.yaml
- .github/workflows/pr_title_check.yaml
Fixes the pr-title-check action by calling it every PR instead of workflow call
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2e49g5a4175l0
> PE-4427: fix(workflow)

- lib/blocs/pin_file/pin_file_bloc.dart
- lib/blocs/pin_file/pin_file_state.dart
- lib/blocs/pin_file/types.dart
- lib/components/pin_file_dialog.dart
- pubspec.lock
- pubspec.yaml
- test/blocs/pin_file_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3n9cco0fce0g8
> PE-4411: Multiple errors concentrated in single modal

- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_hi.arb
- lib/l10n/app_ja.arb
- lib/l10n/app_zh-HK.arb
- lib/l10n/app_zh.arb
- lib/turbo/topup/views/topup_payment_form.dart
- lib/turbo/topup/views/topup_review_view.dart
- lib/utils/split_localizations.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/52rdhhtcpp4t0
> PE-4430: makes a wording to use a placeholder

- lib/cookie_policy_consent/views/cookie_policy_consent_modal.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3o7erl5tddbg0
> PE-4438: makes the text color of cookie modal depend on the theme

- lib/components/new_button/new_button.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7i78ie45m81s0
> PE-2586: corrects usage of divider; sorts the options

- lib/components/side_bar.dart
- lib/l10n/app_en.arb
- lib/utils/logger/logger.dart
- verify if the cellphone has at least one email app client to show the `send email` button 
- fixes download opening the share intent
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5k9tpdjf49v50
> PE-4485: fix(export logs)

- lib/blocs/pin_file/file_id_resolver.dart
- lib/blocs/pin_file/pin_file_bloc.dart
Related PR: #1271
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2tn2g35cruh98
> PE-4486: fallback to HEAD request for missing Content-Type

- README.md
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4ng6lchcdmmoo
> PE-4491: Update README.md

- lib/components/new_button/new_button.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/295pm03vejr68
> PE-4492: Submenu button options appear disabled despite being functional

- lib/components/new_button/new_button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5rugrr9q5todg
> PE-4492: Options order for Plus Button

- lib/components/new_button/new_button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3h5n4lnl48d60
> PE-4505: feat(new button): adds back the hover animation

- lib/components/details_panel.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/256dr1i3kdu30
> PE-4507: fix: details panel on share view

- lib/models/database/database.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/74hs3c8liegb0
> PE-4508: add pinnedDataOwner column in the DB Migration v16 to v17

- lib/components/new_button/new_button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4c7j6hopc2jrg
> PE-4515: fix background color on divider of the new button

- lib/components/new_button/new_button.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/48tqbndrri9v0
> PE-4515: Plus button wrong color

- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/FirstDriveEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/FirstFileEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/LatestDriveEntityWithId.graphql
- lib/services/arweave/graphql/queries/LatestFileEntityWithId.graphql
- lib/services/arweave/graphql/queries/UserDriveEntities.graphql
- lib/utils/arfs_txs_filter.dart
- test/utils/arfs_txs_filter_test.dart
- Filters the ArFS transactions on the client side
- Make the single-item-queries request pages of 10 items until the first one matches.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6ukjoa02tga8o
> PE-4502: filters the arfs transactions in the client side

- lib/components/new_button/new_button.dart
- lib/components/side_bar.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3pfici473r1g0
> PE-4530: makes the new menu options be well aligned when the sidebar is collapsed

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/components/details_panel.dart
- lib/download/multiple_download_bloc.dart
- lib/download/multiple_download_event.dart
- lib/download/multiple_file_download_modal.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- lib/pages/drive_detail/drive_detail_page.dart
- pubspec.lock
- pubspec.yaml
Fixes PE-4539 and PE-4540 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1rga9pd1u8ilo
> PE-4539: incorrect default names for drive and folder downloads

- lib/l10n/app_en.arb
TODO - Edit: we're leaving these for later on
- Remove duplicates
- Remove "sync" (now unused)
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1b2tsqknkb2v8
> PE-4509: updates Eng wordings

- lib/download/download_utils.dart
- lib/download/multiple_download_bloc.dart
- test/download/multiple_download_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3932bl7pgofvo
> PE-4557: implemented multi-file download support for public pins on a private drive

- lib/services/arweave/arweave_service.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4u1cl3is0tgeg
> PE-4556: Cannot log in

- lib/turbo/topup/blocs/payment_form/payment_form_bloc.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/40v1769nuip0o
> PE-4559: makes the refresh button preserve the applied promo code

- android/fastlane/metadata/android/en-US/changelogs/58.txt
- pubspec.yaml
- add release notes on android
- bump version
> PE-4567: release v2.10.0

- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/AllFileEntitiesWithId.graphql
- lib/services/arweave/graphql/queries/DriveEntityHistory.graphql
- lib/services/arweave/graphql/queries/FirstDriveEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/FirstFileEntityWithIdOwner.graphql
- lib/services/arweave/graphql/queries/LatestDriveEntityWithId.graphql
- lib/services/arweave/graphql/queries/LatestFileEntityWithId.graphql
- lib/services/arweave/graphql/queries/UserDriveEntities.graphql
- lib/utils/arfs_txs_filter.dart
- test/utils/arfs_txs_filter_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6h56afqgf9f00
> PE-4502: remove arfs vesion filter

- android/fastlane/metadata/android/en-US/changelogs/60.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0svnbkbec5mhg
> PE-4599: bump version and release notes

- lib/authentication/login/blocs/login_bloc.dart
- lib/authentication/login/views/login_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/26jr4vkqlqing
> PE-4606: check permissions before connecting

- lib/blocs/pin_file/pin_file_bloc.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/28tpsr3nah7u8
> PE-4645: Unable to create Pins in both public and private drive

- lib/blocs/pin_file/pin_file_bloc.dart
- lib/entities/constants.dart
- lib/services/arweave/arweave_service.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7ngs6gc54idlo
> PE-4545: Adds a GQL Tag for public pinned files

- lib/components/drive_create_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5n1q59db7qgn8
> PE-4647: Make the privacy field for Create Drive not change color on Focus

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/78q6arun07560
> PE-4653: fix buttons overflow

- lib/l10n/app_en.arb
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7676ertngfug0
> PE-4661: rename 1.0 speed option to 'Normal'

- lib/components/new_button/new_button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2ipe522snu4ho
> PE-4665: Snapshot creation disabled without ARs

- assets/config/dev.json
- assets/config/prod.json
- assets/config/staging.json
- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/blocs/fs_entry_preview/fs_entry_preview_state.dart
- lib/dev_tools/app_dev_tools.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/services/config/app_config.dart
- lib/utils/constants.dart
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/24mhbda1rrcn0
> PE-4338: initial work on new video player preview (WIP, do not merge)

- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- test/blocs/create_snapshot_cubit_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6mqpvsrn50m2o
> PE-4687: Free snapshots aren't using Turbo as it's expected

- lib/misc/resources.dart
The candidate changes for updating the URL sub-domain of the Feedback Survey Link - `pds-inc`.
> PE-4718: [HOTFIX CANDIDATE] Updates the sub-domain of the feedback survey form URL

- android/fastlane/metadata/android/en-US/changelogs/68.txt
- pubspec.yaml
> PE-4718: hotfix version bump

- lib/utils/show_general_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4jvfj00dbskkg
> PE-4738: fix: Unable to continue drive creation after creating the first drive as a new user

- lib/authentication/login/views/login_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6mqjohe13l5c0
> PE-4786: Makes the wallet address be displayed the first time the JSON wallet gets loaded

- lib/authentication/ardrive_auth.dart
- lib/authentication/login/blocs/login_bloc.dart
- lib/authentication/login/views/login_page.dart
- lib/l10n/app_en.arb
- lib/user/repositories/user_repository.dart
- test/authentication/ardrive_auth_test.dart
- test/authentication/login/blocs/login_bloc_test.dart
- test/user/repositories/user_repository_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1l2lgcfblkooo
> PE-4752: Wallet address in login page PoC

- android/fastlane/metadata/android/en-US/changelogs/68.txt
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6s35k5ahmmlqg
> PE-4718: updates android release notes

- lib/authentication/login/views/login_page.dart
- lib/components/profile_card.dart
- lib/pages/app_router_delegate.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/pages/no_drives/no_drives_page.dart
- lib/pages/shared_file/shared_file_page.dart
- lib/turbo/topup/views/topup_modal.dart
- lib/utils/plausible_event_tracker.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7sjsl6u5o82u0
> PE-4741: Track Plausible events

- lib/components/side_bar.dart
- lib/dev_tools/app_dev_tools.dart
- packages/ardrive_uploader/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/ardrive_uploader/lib/src/turbo_upload_service_web.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5lhuov6rh97uo
> PE-4856: adds the dev tools on mobile

- android/fastlane/metadata/android/en-US/changelogs/75.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2jfllqstfb18g
> PE-4934: Before-Release Preparations

- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3164lltg58fb0
> PE-4930: emit preview unavailable for non-file entities

- android/fastlane/metadata/android/en-US/changelogs/76.txt
- pubspec.yaml
bump pubspec version
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6fn2niuaqnglg
> PE-4960: pre-release tasks

- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- packages/ardrive_uploader/pubspec.yaml
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/05461eo7hc908
> PE-4923: Updates ardrive_io dep

- lib/main.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/utils/mobile_screen_orientation.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/78bm413nmfbk8
> PE-4983: makes the app start on portrait mode

- lib/l10n/app_en.arb
- lib/main.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/utils/mobile_status_bar.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5p9nmcib0jbbo
> PE-4984: Hide controls and status bar when full-screen

- android/fastlane/metadata/android/en-US/changelogs/77.txt
- packages/arconnect/pubspec.yaml
- packages/ardrive_crypto/pubspec.yaml
- packages/ardrive_uploader/example/pubspec.yaml
- packages/ardrive_uploader/pubspec.yaml
- packages/ardrive_utils/pubspec.yaml
- packages/pst/pubspec.yaml
- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3vgegohdjsg40
> PE-5027: chore: bump version and arweave version

- lib/turbo/services/payment_service.dart
- test/services/payment_service_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0t2gffl4oas90
> PE-5146: implements unit tests for the Payment Service class

- lib/l10n/app_en.arb
- lib/turbo/services/payment_service.dart
- lib/turbo/topup/blocs/payment_form/payment_form_state.dart
- lib/turbo/topup/models/payment_model.dart
- lib/turbo/topup/models/price_estimate.dart
- lib/turbo/topup/views/topup_payment_form.dart
- test/services/payment_service_test.dart
- test/turbo/blocs/payment_form/payment_form_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4s0l4nfjo9dlo
> PE-5138: Make Discount Details Match Promo Code in Top Up Modal

- android/fastlane/metadata/android/en-US/changelogs/82.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6sm0ddgsdfsq0
> PE-5174: Before release preparations

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- packages/ardrive_uploader/lib/ardrive_uploader.dart
- packages/ardrive_uploader/lib/src/ardrive_uploader.dart
- packages/ardrive_uploader/lib/src/d2n_streamed_upload.dart
- packages/ardrive_uploader/lib/src/data_bundler.dart
- packages/ardrive_uploader/lib/src/exceptions.dart
- packages/ardrive_uploader/lib/src/factories.dart
- packages/ardrive_uploader/lib/src/streamed_upload.dart
- packages/ardrive_uploader/lib/src/turbo_streamed_upload.dart
- packages/ardrive_uploader/lib/src/turbo_upload_service_web.dart
- packages/ardrive_uploader/lib/src/upload_controller.dart
- packages/ardrive_uploader/lib/src/upload_strategy.dart
- packages/ardrive_uploader/test/factories_test.dart
- decouples the controller from low-level classes like the streamed upload
- refactors on the UploadTask APIs and on the UploadController
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/76dodref8sf88
> PE-4949: (WIP): refactors and unit tests

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3n8btg35aajf0
> PE-5210: feat(upload): remove warning for large uploads on turbo

- lib/components/top_up_dialog.dart
- lib/l10n/app_en.arb
- lib/misc/resources.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ntqnanfsokn0
> PE-5132: adds wording for the app limits

- lib/app_shell.dart
- lib/gift/reedem_button.dart
- lib/l10n/app_en.arb
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/21rq02ru43aa0
> PE-5233: missing tooltip

- lib/pages/no_drives/no_drives_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1gc4enkn8dasg
> PE-5242: add missing gift redemption button to empty drives view

- lib/app_shell.dart
- lib/components/app_top_bar.dart
- lib/components/hide_dialog.dart
- lib/l10n/app_en.arb
- lib/pages/drive_detail/drive_detail_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5igd0r9l2v5v8
> PE-5310: Puts the reveal button as an option in the drive dropdown

- lib/pages/drive_detail/components/drive_detail_data_list.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/63ddd6v0kfl5g
> PE-5317: re-enables multi-select when not showing hidden files

- lib/components/details_panel.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3h58agq6e5vng
> PE-5212: fix(tooltips): add missing tooltips on details panel and preview widgets

- lib/authentication/ardrive_auth.dart
- lib/authentication/login/views/login_page.dart
- lib/blocs/create_snapshot/create_snapshot_cubit.dart
- lib/blocs/file_download/personal_file_download_cubit.dart
- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/blocs/pin_file/file_id_resolver.dart
- lib/blocs/pin_file/pin_file_bloc.dart
- lib/blocs/profile/profile_cubit.dart
- lib/blocs/sync/sync_cubit.dart
- lib/blocs/sync/utils/add_file_entity_revisions.dart
- lib/blocs/sync/utils/sync_drive.dart
- lib/blocs/upload/upload_cubit.dart
- lib/components/create_snapshot_dialog.dart
- lib/components/file_picker_modal.dart
- lib/components/pin_file_dialog.dart
- lib/components/upload_form.dart
- lib/main.dart
- lib/models/daos/profile_dao.dart
- lib/models/database/database.dart
- lib/models/database/database_helpers.dart
- lib/services/config/config_service.dart
- lib/turbo/services/upload_service.dart
- lib/turbo/topup/blocs/topup_estimation_bloc.dart
- lib/turbo/topup/views/topup_payment_form.dart
- packages/arconnect/lib/src/safe_arconnect_action.dart
- Reviewed all the logs. Were removed some logs and changed others. Some logs the id of entities were not important and were removed. No sensitive info was found.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2n4utm0flngl0
> PE-5002: chore: (review logs)

- lib/blocs/hide/hide_bloc.dart
- lib/blocs/hide/hide_state.dart
- lib/blocs/upload/models/payment_method_info.dart
- lib/blocs/upload/payment_method/bloc/upload_payment_method_bloc.dart
- lib/blocs/upload/payment_method/bloc/upload_payment_method_event.dart
- lib/blocs/upload/payment_method/bloc/upload_payment_method_state.dart
- lib/blocs/upload/payment_method/view/upload_payment_method_view.dart
- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/create_snapshot_dialog.dart
- lib/components/payment_method_selector_widget.dart
- lib/components/upload_form.dart
- lib/core/upload/uploader.dart
- lib/main.dart
- test/blocs/upload_cubit_test.dart
- test/core/upload/uploader_test.dart
- abstract the logic for calculating and selecting the payment method
- implemented the Bloc, state and events
- Replaced old component on upload form page
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/41ksr8pahkel8
> PE-5443: refactor select payment modal and abstract to a new component and remove duplicated code

- lib/blocs/drive_detail/drive_detail_cubit.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7fdvh2jjfaol0
> PE-5345: Navigate only through visible images

- lib/components/fs_entry_move_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6e64s54d0pfg0
> PE-5346: makes the form list only visible folders where to move to

- lib/components/upload_form.dart
- packages/ardrive_uploader/lib/src/turbo_upload_service.dart
- packages/ardrive_uploader/lib/src/upload_controller.dart
- packages/ardrive_uploader/lib/src/upload_strategy.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/559nlhckd67pg
> PE-5387: testing finalizing state

- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/components/create_manifest_form.dart
- lib/components/new_button/new_button.dart
- properly verify pending files
- remove unnecessary queries
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2d33fbphl5pt8
> PE-5463: fix(manifest)

- android/fastlane/metadata/android/en-US/changelogs/91.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/49efdrnnqgapg
> PE-5492: pre-release tasks

- lib/main.dart
- lib/sharing/blocs/sharing_file_bloc.dart
- lib/sharing/blocs/sharing_file_state.dart
- lib/sharing/folder_selector/folder_selector.dart
- lib/sharing/sharing_file_listener.dart
Fixes navigation and freezing on intent share upload workflow
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/598orm8svdqig
> PE-5444: fix app freezing on share

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- lib/pages/drive_detail/drive_detail_page.dart
Fixes issue with hiding files that are not meant to be hidden.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2l1klalksmo3g
> PE-5528: concealed files fixes

- lib/sharing/folder_selector/folder_selector.dart
Implements different scroll physics controller
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5agql5d9i7cu8
> PE-5445: scrolling issues

- .github/workflows/production.yaml
- .github/workflows/staging.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/75jbvn0lnp1so
> PE-5538: add source maps generation for staging and prod deploys

- .vscode/settings.json
- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- lib/components/fs_entry_move_form.dart
- lib/components/hide_dialog.dart
- lib/main.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- lib/pages/drive_detail/drive_detail_page.dart
- test/blocs/fs_entry_move_bloc_test.dart
dont move hidden files
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0mknq6mfpv460
> PE-5534: hidden file movement possible

- lib/models/database/database.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2eoi6107cml18
> fix(schema): update schema to v18 to migrate isHidden changes

- android/fastlane/metadata/android/en-US/changelogs/93.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6fbkk0l77knko
> PE-5547: bump version and release notes

- android/app/src/main/AndroidManifest.xml
* Reverts manifest changes introduced in sharing feature that were found to have issues on S22/Android 14
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3fj7n47cbm8i8
> PE-5572: fix JSON file loading and saving on Samsung S22/Android 14

- lib/components/fs_entry_license_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7m1mqfim5ochg
> PE-5577: disable next button if form is invalid

- lib/components/ghost_fixer_form.dart
- fixes the ghost fix not updating the ui
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6raksslj7dhrg
> PE-5584: refresh table when fixing a ghost folder 

- android/fastlane/metadata/android/en-US/changelogs/104.txt
- android/fastlane/metadata/android/en-US/changelogs/105.txt
- pubspec.lock
- pubspec.yaml
- Added file licensing for UDL and Creative Commons.
> PE-5633: release notes and bump version

- lib/components/upload_form.dart
- packages/ardrive_uploader/lib/src/upload_controller.dart
- hide the cancel button if there is no upload in progress
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1prdi6e4v007g
> PE-5397: hiding cancel button

- packages/ardrive_crypto/lib/src/stream_aes.dart
- packages/ardrive_crypto/lib/src/stream_cipher.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3m3heku5pkcuo
> PE-5672: fix GCM encrypted downloads

- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- copy the selected item list instead of passing the reference of the original list.
The root cause was that the original list of selected items was passed by reference. Therefore, when multi-select was disabled, it inadvertently cleared the original selection, affecting subsequent operations that relied on this list.
```dart
onPressed: () {
context.read<FsEntryMoveBloc>().add(
FsEntryMoveSubmit(
folderInView:
state.viewingFolder.folder,
),
);
context
.read<DriveDetailCubit>()
.forceDisableMultiselect = true;
},
```
The issue was identified during the file movement process within private drives. Unlike public drives, which do not require a drive key and therefore finalize UI updates more quickly, private drives were encountering a problem where the list of selected items was cleared …
> PE-5736: fix(move files)

- packages/ardrive_uploader/lib/src/turbo_upload_service.dart
- format code
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6a36kaeota750
> PE-5731:(refactor) format code

- packages/ardrive_uploader/lib/src/turbo_streamed_upload.dart
- packages/ardrive_uploader/lib/src/turbo_upload_service.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6j5q8nmdkvug8
> PE-5731: use new async multipart endpoints

- android/fastlane/metadata/android/en-US/changelogs/112.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7nq2qd9ri01m0
> PE-5761: bump version and proposed release notes

- packages/ardrive_uploader/lib/src/data_bundler.dart
- packages/ardrive_uploader/lib/src/upload_strategy.dart
- packages/ardrive_uploader/lib/src/utils/data_bundler_utils.dart
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4houkptapqn80
> fix uploads to turbo

- lib/components/fs_entry_license_form.dart
- lib/misc/resources.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4te1uhfamh3n8
> PE-5767: fix(license help link)

- android/fastlane/metadata/android/en-US/changelogs/114.txt
- pubspec.yaml
- bump version
- add release notes
> PE-5771: Release notes and bump version

- lib/authentication/ardrive_auth.dart
- lib/entities/entity.dart
- packages/ardrive_logger/lib/ardrive_logger.dart
- packages/ardrive_logger/lib/src/logger.dart
- packages/ardrive_logger/lib/src/untracked_exception.dart
- implements the UntrackedException to filter exceptions before sending to sentry
- filter exceptions on ardrive auth
- filter parse entity exception
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4h5noesnfsk60
> PE-5772: feat(logger)

- lib/pages/drive_detail/components/drive_detail_data_list.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4orobk4o3m1r0
> PE-5792: intermittent visibility issue with license column in folders

- lib/utils/snapshots/snapshot_item_to_be_created.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2ejb31q3g6bj0
> PE-5843: with batching strategy

- android/fastlane/metadata/android/en-US/changelogs/117.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4ksh28127b1h8
> PE-5865: bump version and release notes

- .github/workflows/pr.yaml
- .github/workflows/production.yaml
- .github/workflows/staging.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7cfp7pepb2f0g
> PE-5876: remove minification

- lib/authentication/login/views/login_page.dart
- lib/authentication/login/views/tutorials_view.dart
- lib/authentication/login/views/wallet_created_view.dart
- packages/ardrive_ui/lib/src/styles/colors/colors_new.dart
* diagnosed light mode color issues with design and fixed here
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/51r1re311v0to
> PE-5872: fixing-light-mode-issues

- lib/authentication/login/views/login_page.dart
- lib/authentication/login/views/tutorials_view.dart
- lib/authentication/login/views/wallet_created_view.dart
- lib/misc/resources.dart
- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/FirstTxForWallet.graphql
- lib/utils/pre_cache_assets.dart
- packages/ardrive_ui/lib/src/styles/colors/colors_new.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0liggp1f9kgj0
> PE-5360: new onboarding checkpoint 1

- lib/authentication/login/views/wallet_created_view.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3q34f3i7b118o
> PE-5903: fixes padding on android

- lib/authentication/login/views/login_page.dart
- lib/authentication/login/views/prompt_wallet_view.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2ibjjoh8msbj0
> PE-5359: fix scroll phone

- assets/config/dev.json
- assets/config/prod.json
- assets/config/staging.json
- lib/authentication/login/blocs/login_bloc.dart
- lib/authentication/login/views/login_page.dart
- lib/dev_tools/app_dev_tools.dart
- lib/services/config/app_config.dart
- test/authentication/login/blocs/login_bloc_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/32vbhr2rst0bg
> PE-5952: add a feature flag for metamask login

- lib/misc/resources.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/52rbt5gv788g0
> PE-5962: Update resources.dart

- lib/authentication/login/views/modals/import_wallet_modal.dart
- lib/misc/resources.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2qed6jr4i7irg
> PE-5961: change upload keyfile button text

- lib/authentication/login/blocs/login_bloc.dart
- lib/authentication/login/views/landing_view.dart
- lib/authentication/login/views/login_page.dart
- lib/authentication/login/views/modals/blocking_modals.dart
- lib/authentication/login/views/modals/enter_your_password_modal.dart
- lib/authentication/login/views/modals/import_wallet_modal.dart
- lib/authentication/login/views/modals/secure_your_wallet_modal.dart
- lib/authentication/login/views/prompt_wallet_view.dart
- lib/authentication/login/views/tutorials_view.dart
- lib/authentication/login/views/wallet_created_view.dart
- lib/components/theme_switcher.dart
- lib/utils/plausible_event_tracker/plausible_custom_events.dart
- lib/utils/plausible_event_tracker/plausible_event_tracker.dart
- lib/utils/plausible_event_tracker/plausible_page_view_events.dart
- test/authentication/ardrive_auth_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0g3vplu56ghbo
> PE-5867: plausible event tracking

- android/fastlane/metadata/android/en-US/changelogs/120.txt
- pubspec.yaml
add release notes
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/33grsf6c3ldeo
> PE-5974: release notes android

- android/fastlane/metadata/android/en-US/changelogs/121.txt
- pubspec.yaml
bump version
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/05bkve502m3jg
> PE-5980: bump app version

- lib/authentication/login/views/tutorials_view.dart
* Checks mounted state before using setState and also modifies how it sets loading to false
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7mte0j1p2aleg
> PE-5985: Fix exception when changing pages on Tutorial view

- lib/authentication/ardrive_auth.dart
- test/authentication/ardrive_auth_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6vibv4o3bd6jg
> PE-6033: fix Login Failure After Switch Wallets on the Login Page

- lib/authentication/login/blocs/login_bloc.dart
- test/authentication/login/blocs/login_bloc_test.dart
dont show tutorial if the user has drives
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3d5i3rng01u68
> PE-6073: update login_bloc.dart

- android/fastlane/metadata/android/en-US/changelogs/124.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1n18a6gm44eho
> PE-6079: bump version and release notes

- android/fastlane/metadata/android/en-US/changelogs/124.txt
- android/fastlane/metadata/android/en-US/changelogs/125.txt
- assets/config/prod.json
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6sp7l0fgen9fg
> PE-6085: release ar drive v2.43.0

- android/fastlane/metadata/android/en-US/changelogs/126.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2jl76ftp9sku8
> PE-6114: bump version and release notes

- lib/pages/no_drives/no_drives_page.dart
- lib/utils/plausible_event_tracker/plausible_custom_events.dart
- lib/utils/plausible_event_tracker/plausible_event_tracker.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1170t8ctiag88
> PE-6120: feat(plausible): events create drive

- lib/search/search_modal.dart
- lib/utils/plausible_event_tracker/plausible_page_view_events.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5bbpj8f8thieg
> PE-6119: add plausible events for search

- lib/core/crypto/crypto.dart
- lib/utils/logger.dart
- packages/ardrive_crypto/lib/ardrive_crypto.dart
- packages/ardrive_crypto/lib/src/entities.dart
- packages/ardrive_crypto/lib/src/exceptions.dart
- packages/ardrive_crypto/lib/src/keys.dart
- packages/ardrive_logger/lib/src/logger.dart
- test/utils/logger_test.dart
- enhance error handling on encryption and decryption
- filter `TransactionDecryptionException` for buggy versions
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/13f4smmp248dg
> PE-5608: feat(logging)

- android/fastlane/metadata/android/en-US/changelogs/127.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0udctv4mgcse8
> PE-6137: bump version and release notes

- lib/app_shell.dart
- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/create_manifest/create_manifest_state.dart
- lib/blocs/upload/payment_method/view/upload_payment_method_view.dart
- lib/components/create_manifest_form.dart
- lib/components/payment_method_selector_widget.dart
- lib/components/progress_bar.dart
- lib/components/progress_dialog.dart
- lib/components/upload_form.dart
- lib/core/arfs/exceptions.dart
- lib/core/arfs/repository/file_repository.dart
- lib/core/arfs/repository/folder_repository.dart
- lib/core/arfs/utils/arfs_revision_status_utils.dart
- lib/entities/manifest_data.dart
- lib/manifest/domain/exceptions.dart
- lib/manifest/domain/manifest_repository.dart
- lib/models/daos/drive_dao/drive_dao.dart
- packages/ardrive_ui/lib/src/components/modal.dart
- packages/ardrive_uploader/lib/src/upload_controller.dart
- test/core/arfs/folder_repository_test.dart
- test/entities/manifest_data_test.dart
- test/manifest/domain/manifest_repository_test.dart
- test/test_utils/mocks.dart
- implements the CreateManifestRepository to abstract the logic on cubit
- Refactored the CreateManifestForm widget
- enhanced api on FileRepository
- enhanced api on FolderRepository
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5a51bbt5goou8
> PE-6115: feat(upload manifest with turbo)

- android/fastlane/metadata/android/en-US/changelogs/128.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/44sklbhgs6os8
> PE-6146: bump version and release notes

- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
- packages/ardrive_uploader/lib/ardrive_uploader.dart
- packages/ardrive_uploader/lib/src/ardrive_uploader.dart
- packages/ardrive_uploader/lib/src/arfs_upload_metadata.dart
- packages/ardrive_uploader/lib/src/data_bundler.dart
- packages/ardrive_uploader/lib/src/exceptions.dart
- packages/ardrive_uploader/lib/src/metadata_generator.dart
- packages/ardrive_uploader/lib/src/turbo_streamed_upload.dart
- packages/ardrive_uploader/lib/src/upload_controller.dart
- packages/ardrive_uploader/lib/src/upload_dispatcher.dart
- packages/ardrive_uploader/lib/src/upload_strategy.dart
- packages/ardrive_uploader/lib/src/upload_task.dart
- packages/ardrive_uploader/lib/src/utils/data_bundler_utils.dart
- packages/ardrive_uploader/test/arfs_upload_metadata_test.dart
- packages/ardrive_uploader/test/metadata_generator_test.dart
- packages/ardrive_uploader/test/upload_task_test.dart
- packages/ardrive_uploader/test/utils/data_bundler_utils_test.dart
- packages/ardrive_utils/lib/src/entity_tag.dart
- Enhance error handling
- Fixes an issue with upload folders (more in the pr comments)
- Removed some logs
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1iofrch7u28so
> PE-5911: feat(upload)

- lib/blocs/drives/drives_cubit.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5qubggumjegmg
> PE-6217: update drives_cubit.dart

- lib/components/folder_create_form.dart
- lib/components/pin_file_dialog.dart
- lib/components/progress_dialog.dart
- lib/pages/drive_detail/components/drive_detail_folder_empty_card.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/shared/components/plausible_page_view_wrapper.dart
- lib/utils/plausible_event_tracker/plausible_custom_events.dart
- lib/utils/plausible_event_tracker/plausible_event_tracker.dart
- lib/utils/plausible_event_tracker/plausible_page_view_events.dart
- packages/ardrive_ui/lib/src/components/modal.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6vbacts030lto
> PE-6147: feat(empty state): implement empty state

- lib/download/ardrive_downloader.dart
- lib/drive_explorer/thumbnail/repository/thumbnail_repository.dart
- lib/drive_explorer/thumbnail/thumbnail.dart
- lib/drive_explorer/thumbnail/thumbnail_bloc.dart
- lib/drive_explorer/thumbnail/thumbnail_event.dart
- lib/drive_explorer/thumbnail/thumbnail_state.dart
- lib/entities/license_assertion.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6ols61ac4m4ag
> thumbnails poc

- lib/components/details_panel.dart
- lib/dev_tools/thumbnail_generator_poc.dart
- lib/drive_explorer/thumbnail/repository/thumbnail_repository.dart
- lib/drive_explorer/thumbnail/thumbnail.dart
- lib/drive_explorer/thumbnail/thumbnail_state.dart
- lib/drive_explorer/thumbnail_creation/bloc/thumbnail_creation_bloc.dart
- lib/drive_explorer/thumbnail_creation/bloc/thumbnail_creation_event.dart
- lib/drive_explorer/thumbnail_creation/bloc/thumbnail_creation_state.dart
- lib/drive_explorer/thumbnail_creation/page/thumbnail_creation_modal.dart
- lib/entities/file_entity.dart
- lib/entities/license_assertion.dart
- lib/main.dart
- lib/models/enums.dart
- lib/models/file_entry.dart
- lib/models/file_revision.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- lib/pages/drive_detail/drive_detail_page.dart
- packages/ardrive_uploader/lib/src/ardrive_uploader.dart
- packages/ardrive_uploader/lib/src/arfs_upload_metadata.dart
- packages/ardrive_uploader/lib/src/data_bundler.dart
- packages/ardrive_uploader/lib/src/upload_strategy.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7ts8ctfqsqrvo
> PE-6281: upload images with thumbnails

- android/fastlane/metadata/android/en-US/changelogs/131.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5091lidref7k0
> PE-6348: bump version and release notes

- android/fastlane/metadata/android/en-US/changelogs/132.txt
- packages/ardrive_uploader/lib/src/ardrive_uploader.dart
- packages/ardrive_uploader/lib/src/constants.dart
- packages/ardrive_uploader/lib/src/data_bundler.dart
- packages/ardrive_uploader/lib/src/upload_dispatcher.dart
- pubspec.yaml
- fix thumbnails uploads and catch error when the thumbnail generation fails
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6e8sopv4donq8
> PE-6360: fix(thumbnails)

- web/index.html
New link preview: 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/27k6m3ign3u4g
> PE-6391: update index.html

- lib/pages/drive_detail/components/drive_detail_data_list.dart
- pubspec.yaml
> hotfix: share page

- lib/blocs/data_export/data_export_cubit.dart
- lib/components/csv_export_dialog.dart
- test/blocs/data_export_cubit_test.dart
- test/snapshots/data_export_snapshot.dart
adds the Parent Folder Name column
adds the Status column
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5vnf8pj2hv5b0
> PE-6189: feat(drive export)

- lib/app_shell.dart
- lib/drive_explorer/multi_thumbnail_creation/multi_thumbnail_creation_warn_modal.dart
- pubspec.yaml
add warning modal before starts the creation of thumbs
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/35nn1mmov5sf0
> feat(thumbnails)

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/pages/app_router_delegate.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6m63m1brkh9do
> PE-6438: update drive_dao.dart

- lib/blocs/create_manifest/create_manifest_cubit.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1tb80jhm71kcg
> PE-6452: avoids check conflicts when wrong state

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/core/arfs/repository/drive_repository.dart
- lib/pages/app_router_delegate.dart
- test/core/arfs/drive_repository_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7thqatqd5ed9o
> PE-6455: fix state error

- lib/authentication/login/views/login_page.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/daos/drive_dao/exception.dart
- lib/sync/domain/cubit/sync_cubit.dart
- lib/sync/domain/repositories/sync_repository.dart
- packages/ardrive_logger/lib/src/ardrive_context.dart
- packages/ardrive_logger/lib/src/logger.dart
- Add the ArDriveContext class to enhance logging
- handle errors on DriveDAO class with its own exception
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5hd7l8ag46jpo
> PE-6464: enhance error handling and logging

- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/blocs/fs_entry_preview/image_preview_notification.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
proper handle null values on image preview
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2ardvvtjo66qo
> PE-6472: feat(image preview)

- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/blocs/fs_entry_preview/image_preview_notification.dart
- lib/pages/drive_detail/components/fs_entry_preview_widget.dart
- packages/ardrive_uploader/lib/src/d2n_streamed_upload.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2bnp72aklf5e0
> PE-6473: enhance log for bundle upload exception

- lib/blocs/drive_attach/drive_attach_cubit.dart
- lib/blocs/upload/upload_cubit.dart
- lib/services/arweave/arweave_service.dart
- lib/services/arweave/arweave_service_exception.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/27g8dtad74i10
> PE-6471: refactor on error method at drive attach cubit to avoid stack overflow error stack overflow

- lib/main.dart
- lib/pages/drive_detail/drive_detail_page.dart
- lib/sync/data/snapshot_validation_service.dart
- lib/sync/domain/repositories/sync_repository.dart
- lib/utils/snapshots/snapshot_item.dart
- validate snapshot existence before syncing from snapshots
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/11ohs6433ophg
> PE-6517: feat(snapshots)

- android/fastlane/metadata/android/en-US/changelogs/142.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3df67aceuimro
> PE-6525: bump version

- lib/blocs/upload/upload_cubit.dart
- lib/components/create_manifest_form.dart
- lib/components/upload_form.dart
- lib/core/upload/uploader.dart
- lib/services/config/config_fetcher.dart
- test/blocs/upload_cubit_test.dart
- test/core/upload/uploader_test.dart
- test/services/config/config_fetcher_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/73ukv42kudu98
> PE-6559: feat(upload): only display thumbnail checkbox when has image

- lib/arns/presentation/assign_name_bloc/assign_name_bloc.dart
- lib/arns/presentation/assign_name_modal.dart
- if no undernames available, display the No undernames option
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1i1v3fj1fj34o
> PE-6671: fix(assign name)

- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/46f8ek5o8q7jg
> PE-6654: fix license plus arns name

- android/fastlane/metadata/android/en-US/changelogs/147.txt
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5vso17qjg8548
> PE-6687: add release notes

- android/fastlane/metadata/android/en-US/changelogs/148.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0lo6rph6meif0
> PE-6700: add release notes and bump version

- lib/turbo/services/payment_service.dart
- test/services/payment_service_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/00brvu6ms1k10
> PE-6719: use public endpoint fetching turbo balance

- android/fastlane/metadata/android/en-US/changelogs/151.txt
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3ja3ojf26vjuo
> PE-6731: Release ArDrive App v2.54.1

- android/fastlane/metadata/android/en-US/changelogs/154.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5lkldgjlvtu10
> PE-6789: add release notes and bump version for release v2.54.4

- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
organize upload cubit code
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/11is6cp3gsmd8
> PE-6787: refactor(upload cubit)

- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
- lib/core/upload/domain/repository/upload_repository.dart
- lib/main.dart
- lib/utils/dependency_injection_utils.dart
- packages/ardrive_uploader/lib/src/metadata_generator.dart
- test/blocs/upload_cubit_test.dart
- test/core/upload/domain/repository/upload_repository_test.dart
- test/test_utils/utils.dart
Refactors the upload cubit abstracting the following methods:
1. uploadFiles
2. uploadFolders
It also abstracts the logic to save the files/folders into db.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5fql7jqeu4h7g
> PE-6788: implement upload repository

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- lib/core/upload/domain/repository/upload_repository.dart
- lib/pages/drive_detail/components/drive_detail_data_list.dart
- lib/pages/drive_detail/components/drive_explorer_item_tile.dart
- lib/utils/dependency_injection_utils.dart
- test/blocs/upload_cubit_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4rh519flsvdlg
> PE-6619: no loading feedback while verifying failed uploads updated

- android/fastlane/metadata/android/en-US/changelogs/155.txt
- lib/blocs/upload/upload_cubit.dart
- lib/components/upload_form.dart
- lib/drive_explorer/thumbnail/repository/thumbnail_repository.dart
- lib/sync/domain/repositories/sync_repository.dart
- pubspec.yaml
- test/blocs/upload_cubit_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6hci6f65fdh3g
> PE-6805: preview link retains old txid after new file upload

- lib/components/side_bar.dart
- packages/ardrive_ui/lib/src/components/scroll_bar.dart
- update text styles
- align items with
- update scrollbar
Before:
https://github.com/user-attachments/assets/c28bc4b1-acd2-4627-8219-33cd5b3adaaf
Now:
https://github.com/user-attachments/assets/447c60af-2ebc-44b2-9b1b-06db8eb9f442
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/60iqo87hbe2n0
> PE-6853: feat(side bar)

- packages/ardrive_ui/lib/src/components/check_box.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0nevbm10k5lv8
> PE-6783: fix checkbox size

- lib/components/payment_method_selector_widget.dart
- lib/components/upload_form.dart
- packages/ardrive_ui/lib/src/components/check_box.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/04kf301iaj538
> PE-6783: small UI fixes

- lib/authentication/login/views/modals/enter_your_password_modal.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5e3kipaerp9p0
> fix button height mobile

- .github/workflows/test.yml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/50t5npg8halto
> PE-6951: update test.yml

- lib/utils/plausible_event_tracker/plausible_event_tracker.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0tjc1plem9glo
> PE-6950: filter out from sentry string plausible response error client exception xml http request error

- lib/pages/drive_detail/drive_detail_page.dart
fix hide state on mobile
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/56a3pi9h97kg8
> PE-7037: fix hide state on mobile

- android/fastlane/metadata/android/en-US/changelogs/159.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2fvqu7a8n4ai8
> PE-7043: bump version and release notes

- lib/components/details_panel.dart
- lib/components/drive_share_dialog.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3252qb774iqh0
> PE-6898: update share drive style

- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/pages/drive_detail/drive_detail_page.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7kd3co5et2850
> fix(attach drives)

- lib/blocs/upload/upload_cubit.dart
- lib/main.dart
- lib/services/arweave/arweave_service.dart
…rns names
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0mmvsvtqau60g
> PE-7124: save drivekey in memory and fix upload failure loading arns names

- lib/blocs/upload/upload_cubit.dart
- lib/blocs/upload/upload_state.dart
- lib/components/upload_form.dart
- lib/services/arweave/arweave_service.dart
- lib/services/arweave/graphql/queries/LicenseDataBundled.graphql
- lib/utils/is_custom_manifest.dart
- test/utils/is_custom_manifest_test.dart
- implement method to verify if the file is a custom manifest
- add checkbox on upload form to user set the file as a manifest
- upload file with the manifest content type
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/02a5g9lrg67v8
> PE-7106: feat(custom manifest)

- pubspec.lock
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0p33sud2ebb1o
> bump ardrive_io version

- lib/components/profile_card.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7el4a2cjrclsg
> PE-7223: change tIO Tokens to tARIO

- android/fastlane/metadata/android/en-US/changelogs/167.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6tlj3jjpnm7jo
> PE-7258: bump version and release notes

- lib/components/app_top_bar.dart
- lib/components/profile_card.dart
- packages/ardrive_ui/lib/src/components/button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/023vrlopagc38
> fix alignment

- android/fastlane/metadata/android/en-US/changelogs/169.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5ngmlk0535ukg
> PE-7294: release notes and bump version

- lib/blocs/drive_rename/drive_rename_cubit.dart
- lib/components/drive_rename_form.dart
- show warning if drive name already exists
- update modal styles
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5ol71aski7pvo
> PE-7408: fix(rename drive)

- android/fastlane/metadata/android/en-US/changelogs/171.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1vqu864tq2u3g
> PE-7410: bump version and release notes

- lib/authentication/login/views/modals/secure_your_wallet_modal.dart
- change the secure your wallet description
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/20mcp6qspt9cg
> PE-7470: feat(login)

- lib/arns/data/queries/arns_queries.drift
- lib/arns/domain/arns_repository.dart
- lib/blocs/drive_detail/drive_detail_cubit.dart
- lib/blocs/file_share/file_share_cubit.dart
- lib/blocs/folder_create/folder_create_cubit.dart
- lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
- lib/blocs/fs_entry_license/fs_entry_license_bloc.dart
- lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
- lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
- lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
- lib/blocs/ghost_fixer/ghost_fixer_cubit.dart
- lib/blocs/hide/hide_bloc.dart
- lib/blocs/upload/upload_cubit.dart
- lib/core/arfs/repository/file_repository.dart
- lib/core/arfs/repository/folder_repository.dart
- lib/manifest/domain/manifest_repository.dart
- lib/models/daos/drive_dao/drive_dao.dart
- lib/models/database/database.dart
- lib/models/queries/drive_queries.drift
- lib/models/tables/drives.drift
- lib/models/tables/file_entries.drift
- lib/models/tables/folder_entries.drift
- lib/search/domain/repository/search_repository.dart
- lib/search/search_modal.dart
- lib/search/search_result.dart
- lib/sharing/folder_selector/folder_selector_bloc.dart
- lib/sync/domain/repositories/sync_repository.dart
- test/search/domain/repository/search_repository_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/12m6i8ue318r8
> PE-7375: optimize search performance and return results for an ArNS name

- .gitignore
- lib/arns/domain/arns_repository.dart
- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/create_manifest/create_manifest_state.dart
- lib/components/create_manifest_form.dart
- lib/main.dart
- packages/ario_sdk/lib/src/implementations/ario_sdk_web.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0b6k70ts0sg50
> add arns timeout

- lib/components/details_panel.dart
- lib/utils/is_supported_image_type_for_preview.dart
- test/utils/is_supported_image_type_for_preview_test.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4bau9a3m12lo8
> fix(thumbnail): remove option to create a thumbnail if no write permissions

- lib/user/download_wallet/download_wallet_modal.dart
New Modal
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4pc0cep4c1b88
> PE-6959: Update Download Wallet Modal

- lib/utils/graphql_retry.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1ruua0o3e7oto
> PE-7803: fix retry logic for graphql calls

- android/fastlane/metadata/android/en-US/changelogs/182.txt
- android/fastlane/metadata/android/en-US/changelogs/183.txt
- lib/turbo/services/payment_service.dart
- lib/turbo/utils/get_signature_headers_for_turbo.dart
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6alf0ig7jr8d8
> PE-7804:  Bump version and release notes + sync dev with master

- lib/pages/app_router_delegate.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3np7e9imth53o
> PE-5199: fix(sync mobile) change colors of the snackbar to make it visible

- lib/blocs/upload/upload_cubit.dart
- lib/components/profile_card.dart
- lib/components/side_bar.dart
- packages/ardrive_logger/lib/src/logger.dart
- packages/ardrive_logger/pubspec.yaml
Fixes the issue: 'Unable to reopen 'Assign ArNS Name' modal after closing'
- Remove unnecessary reset of _showArnsNameSelectionCheckBoxValue in cancelArnsNameSelection
https://github.com/user-attachments/assets/54d96cc3-bafd-43c0-96af-926660b5337e
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0r8r339g45nfg
> PE-7047: fix(assign arns name to file)

- lib/components/side_bar.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3c9mubie1n09g
> PE-7849: feat(drive explorer) close drawer when selecting a drive

- lib/blocs/create_manifest/create_manifest_cubit.dart
- lib/blocs/create_manifest/create_manifest_state.dart
- lib/components/create_manifest_form.dart
- lib/components/new_button/new_button.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0is5o8fd54m68
> PE-7851: feat(manifest) change order to first select location then the name

- lib/pages/drive_detail/components/drive_file_drop_zone.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5jf7gkdk96nb8
> PE-7838: update modal styles drag n drop folder error message

- packages/ardrive_ui/lib/src/components/data_table/data_table.dart
- packages/ardrive_utils/lib/src/app_platform.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/049iv3vn8lua8
> PE-7846: fix(multiselect) use ctrl on windows machine instead of windows key

- lib/components/create_manifest_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/20rb9v72qh0so
> PE-7884: fix(manifest) data table not updating after inserting the manifest

- lib/blocs/drive_create/drive_create_cubit.dart
- lib/components/drive_create_form.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/035d166ef9u6o
> PE-8014: don't report drive creation as successful in failure scenarios

- android/fastlane/metadata/android/en-US/changelogs/187.txt
- pubspec.yaml
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/63gou0do624ao
> PE-8020: Release v2.67.5

- .github/workflows/production.yaml
- deploy/package.json
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/43ps2cuiufok8
> PE-8053: update permaweb-deploy to v2

- lib/components/profile_card.dart
- lib/components/settings_popover.dart
- lib/gar/domain/repositories/gar_repository.dart
- lib/gar/presentation/bloc/gar_bloc.dart
- lib/gar/presentation/bloc/gar_event.dart
- lib/gar/presentation/bloc/gar_state.dart
- lib/gar/presentation/widgets/gar_modal.dart
- lib/gar/presentation/widgets/gateway_input_modal.dart
- lib/gar/utils/gateway_validator.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/31la8pee9q1l0
> PE-8519: add editable text field for gateway entry and move gateway selector to secondary modal
