assets/config/dev.json
lib/blocs/drive_create/drive_create_cubit.dart
lib/blocs/upload/file_upload_handle.dart
lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/app_drawer/app_drawer.dart
lib/components/upload_form.dart
lib/entities/drive_entity.dart
lib/entities/entity.dart
lib/entities/file_entity.dart
lib/entities/folder_entity.dart
lib/services/arweave/arweave_service.dart
lib/services/crypto/entities.dart
pubspec.lock
pubspec.yaml

By using data bundles for actions that require multiple transactions at once we can:
- Make said actions atomic and avoid problems with dropped transactions resulting in invalid state.
- Increase the throughput for the number of transactions we can perform on the network.
- Support multi-file uploads in a much simpler fashion.

Use data bundles and implement multi-file uploads

---

lib/blocs/profile/profile_state.dart
lib/components/profile_overlay.dart
lib/pages/app_route_information_parser.dart
lib/pages/app_route_path.dart
lib/pages/app_router_delegate.dart

This PR adds an explicit path for a user to sign in with at `/sign-in` and also fixes a bug with the user not being redirected to sign in when logging out.

fix: user not being redirected to sign in when logging out

---

lib/blocs/fs_entry_activity/fs_entry_activity_cubit.dart
lib/blocs/sync/sync_cubit.dart
lib/models/daos/drive_dao/drive_dao.dart
lib/models/file_revision.dart
lib/models/folder_revision.dart
lib/models/queries/drive_queries.moor
lib/models/tables/all.moor
lib/models/tables/drives.moor
lib/models/tables/file_entries.moor
lib/models/tables/file_revisions.moor
lib/models/tables/folder_entries.moor
lib/models/tables/folder_revisions.moor
lib/models/tables/network_transactions.moor
lib/pages/drive_detail/components/fs_entry_side_sheet.dart

This PR moves the status of revision transaction into their own model in the database which simplifies queries and reduces code duplication.

refactor: move transactions into their own database table

---

lib/blocs/drive_create/drive_create_cubit.dart
lib/blocs/folder_create/folder_create_cubit.dart
lib/blocs/fs_entry_move/fs_entry_move_cubit.dart
lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
lib/blocs/sync/sync_cubit.dart
lib/entities/drive_entity.dart
lib/entities/entity.dart
lib/entities/file_entity.dart
lib/entities/folder_entity.dart
lib/models/daos/drive_dao/drive_dao.dart
lib/models/file_revision.dart
lib/models/folder_revision.dart
lib/services/arweave/arweave_service.dart

This PR makes it so that revisions made to folders/files are tracked before they are mined onto the network.
It does not optimistically add revisions for newly uploaded files.

fix: revisions weren't optimistically added for tracking

---

lib/blocs/profile/profile_cubit.dart
lib/blocs/profile/profile_state.dart
lib/blocs/sync/sync_cubit.dart
lib/blocs/upload/upload_cubit.dart
lib/services/arweave/arweave_service.dart
lib/services/arweave/graphql/queries/PendingTxFees.graphql
pubspec.lock

This PR makes the wallet balance displayed in the app account for any pending transaction fees as opposed to just the wallet balance which isn't accurate if there are unconfirmed transactions.
It also makes it so that the balance is refreshed on every sync and after every upload.

ux: optimistically calculate wallet balance

---

lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/upload_form.dart

This PR prevents uploads for files larger than 1.25 GB which can cause browser buffer allocation issues.

feat: prevent uploads of files too large for browser memory

---

lib/blocs/drive_attach/drive_attach_cubit.dart
lib/blocs/drive_create/drive_create_cubit.dart
lib/blocs/drive_detail/drive_detail_cubit.dart
lib/blocs/file_download/personal_file_download_cubit.dart
lib/blocs/file_download/shared_file_download_cubit.dart
lib/blocs/folder_create/folder_create_cubit.dart
lib/blocs/fs_entry_activity/fs_entry_activity_cubit.dart
lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
lib/blocs/fs_entry_move/fs_entry_move_cubit.dart
lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
lib/blocs/sync/sync_cubit.dart
lib/blocs/upload/upload_cubit.dart

This PR prints errors caught and passed to the onError() function of cubits as `bloc` does not do this for us, making it so that errors are simply swallowed.

nit: print errors passed to cubit onError()

---

lib/theme/theme.dart
pubspec.lock
pubspec.yaml

Incorrect colors caused by breaking change in ThemeData secondaryColor property. 
Use colorscheme instead of secondary color.

fix: incorrect textfield label color RM-300

---

lib/blocs/sync/sync_cubit.dart

During sync, gracefully handle the situation that an entity's parent folder is missing.  This can happen temporarily while we are still retrieving data, for instance.  Without this change, the sync will abort and fail, even if the parent folder is actually there and would be added in later.

Properly handle a missing parent folder

---

lib/models/queries/drive_queries.moor

Reworks the query that fetches folders based on paths. While previously it would do a wildcard search for folders inside a folder, now it gets the parent folder id and uses that to fetch the folders inside instead. This is more accurate and doesn't result in looping paths and weird folder hierarchy.

task: update folders in folder query PE-626

---

lib/blocs/profile/profile_cubit.dart
lib/blocs/sync/sync_cubit.dart
lib/components/upload_form.dart

Adds an isOverlayOpen property to ProfileCubit which should be set when an overlay like the file picker is shown.
In this case it's set when the file picker is shown for file upload. We use the property then to skip sync so it doesn't interfere with uploads.

task: skip sync when overlays are open PE-31

---

lib/pages/drive_detail/components/drive_detail_data_table.dart
lib/pages/drive_detail/drive_detail_page.dart

UI tweaks to prevent folder and file names from overlapping with other columns of the data table.

fix: Fix folder name overlap PE-22

---

lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
lib/l11n/validation_messages.dart

When renaming a file, we now enforce that the new name should be different from the current name.

task: add validation message for identical name on rename PE-665

---

lib/blocs/sync/sync_cubit.dart

Checks whether the user owns the drive and if they don't skips ghost creation.

refactor: don't create ghosts for attached drive PE-959

---

lib/blocs/drive_detail/drive_detail_cubit.dart
lib/components/app_drawer/app_drawer.dart

Stops sync from resetting the current rows per page option.
Also took the opportunity to update the placeholder widget for version, which stops the widgets on top from jumping around.

PE 978/Dont reset rows per page on sync

---

lib/blocs/sync/sync_cubit.dart

Updates pending transaction status confirmation threshold to 8 hours.
Looks back 240 blocks on every sync after the first.

PE 1067/handle 8 hour unbundling time

---

lib/blocs/drive_attach/drive_attach_cubit.dart
lib/blocs/drive_attach/drive_attach_state.dart
lib/components/drive_attach_form.dart
lib/l11n/validation_messages.dart
lib/models/daos/drive_dao/drive_dao.dart
lib/pages/app_route_information_parser.dart
lib/pages/app_route_path.dart
lib/pages/app_router_delegate.dart
lib/services/arweave/arweave_service.dart
test/blocs/drive_attach_cubit_test.dart

Adds support for attaching private drives both through the attach form and through a shared link.
Suggested Review Order:
1. drive_attach_cubit.dart
2. drive_dao.dart
(Added support for attaching private drives)
3. app_route_information_parser.dart, app_router_delegate.dart, app_route_path.dart 
(Updated routing to support driveKey)
5. drive_attach_cubit_test.dart
(Expanded drive attach cubit tests)
To support attaching private drives, the writeDriveEntity function was updated to take in a driveKey and to write private drives to the database. A getDrivePrivacyForId function was added to arweave_service to fetch the privacy tag value of a drive with the given drive id.
A new driveKey field was added to drive_attach_form and drive_attach_cubit which is only visible when the given drive id …

PE 1062/Attach private drives

---

lib/pages/drive_detail/components/fs_entry_side_sheet.dart

Corrects the type used in the folder info state.

fix(drive_detail): fix folder info metadata tx not being shown PE-1093

---

lib/pages/drive_detail/components/fs_entry_side_sheet.dart

Fixes a bug where the incorrect metadata, data and bundle tx ids were shown in the info panel.

fix(drive_detail): show txs from correct revision PE-905

---

lib/blocs/drive_detail/drive_detail_state.dart
lib/pages/drive_detail/components/drive_detail_data_table.dart

Adds equatable bust to the drive detail load state for the drive table object key to compare equality.
A widget will only re-render if the key is different.

fix(drive_detail): fix changed state not updating data table PE-1084

---

lib/pages/drive_detail/components/custom_paginated_data_table.dart
lib/pages/drive_detail/components/drive_detail_data_table.dart
lib/pages/drive_detail/drive_detail_page.dart

Uses a key only in the CustomDataTable widget to avoid scroll and page reset. Removes all other keys from the drive data table.

refactor: add tableKey property to CustomDataTable PE-1109

---

lib/components/upload_form.dart

Align the buttons SKIP - CANCEL - REPLACE.
The TextButton width depends directly on the text inside. So, to align we need to pass a fixed width. 
Before:
Now:
Thanks, @agsuy

Pe 1121 fix buttons alignment

---

lib/components/drive_share_dialog.dart

Fixes the public drive share link generation. 
While working on the private drive sharing we made the generate link function for the public drives synchronous (not async), causing the BlocListener to not fire when the link was generated and the state emitted.
In this fix, we set the share link on the controller in the builder instead.

fix: fix public drive share link PE-1120

---

lib/models/file_entry.dart

This PR preserves the `dataContentType` field on files when performing rename / move actions

fix(file revision): Pass dataContentType on rename and move actions PE-1110

---

lib/blocs/upload/enums/conflicting_files_actions.dart
lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/upload_form.dart
lib/pages/drive_detail/components/drive_file_drop_zone.dart
lib/utils/upload_plan_utils.dart
test/blocs/upload_cubit_test.dart
test/test_utils/mocks.dart
web/index.html

When a user uploads files to a folder, a check is made to see if any existing file names conflict with the files being uploaded.  The user only has the option to replace the existing files and overwrite them with the new data.
Basically, it was added the `SKIP` button capability - it will ignore the conflicting files; And rename the `CONTINUE` button to `REPLACE` - this one still with the same behavior.
This PR intends to implement the tests, specifically UploadCubit. To do so, I've needed to refactor some code:
I moved the function `xfilesToUploadPlan` from `UploadCubit` to another class which was a hard function to mock. I called it UploadPlanUtils but I'm wondering about a better name.
I've changed the initialization of the object. Once we couldn't wait for the object initialization, …

Pe-1003 skip file conflicts on upload

---

lib/l10n/app_en.arb

Text at the activity section for `Folder` and `File` now uses the correct placeholder

PE-1195: corrects text with wrong placeholder

---

lib/components/app_drawer/app_drawer.dart
lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/misc/resources.dart
lib/pages/drive_detail/components/custom_paginated_data_table.dart
lib/pages/profile_auth/components/profile_auth_add_screen.dart
lib/pages/profile_auth/components/profile_auth_prompt_wallet_screen.dart
web/index.html

**This PR...**
- Adds the missing keys at app_es.arb
- So the Back and Next buttons on the onboarding page are translated
- The form validation messages are translated 
- The manifest creation form is fully translated
- Fixes a Spanish typo: "Aplicación" at the onboarding page
- Declares insufficientARWarning and displayedPaginatedData keys in both ARB files
- So the "Insufficient Funds" warning is translated
- The paginated data count is translated: {from} - {to} of {total}
- Temporarily adds the keys aggreeToTerms_main, aggreeToTerms_link, welcomeTo_main, and welcomeTo_description directly in the code as those has a direct order relationship (1 to 1) between en and es. That will be dynamically handled in a [following-up work PE-1125](https://ardrive.atlassian.net/browse/PE-1125) when …

PE-1221: Missing Spanish translations

---

lib/services/arweave/arweave_service.dart
lib/services/arweave/graphql/queries/DriveEntityHistory.graphql

Split the getNewEntitiesForDrive into smaller functions to change the sync algorithm order.
This function was split in two functions:
- getAllTransactionsFromDrive
- createDriveEntityHistoryFromTransactions
Most of the logic was reused.

PE 1343 -Split getNewEntitiesForDrive function into smaller functions

---

lib/components/app_drawer/app_drawer.dart
lib/l10n/app_en.arb

If the user has no funds the button, `NEW` will be disabled and he won't be capable of attaching drives public drives. 
As no fund is required to do that, the button `NEW` will be enabled but the dropdown's options that are required to have funds will be disabled and will show a helpful message.
The disabled items:
- Create Drive 
- Create Folder
- Create Manifest
- Upload Files
- Upload Folder

fix: Allow attaching drives on empty wallets without drives

---

lib/blocs/drives/drives_cubit.dart
lib/pages/app_router_delegate.dart

While you’re creating a new Drive and there is another created drive , and finishing the creation of the drive. The drive selected won’t be the newly created one.
When create another Drive, change the Drive view to this one

fix: When create another Drive, change the Drive view to this one PE-1421

---

lib/pages/drive_detail/components/fs_entry_side_sheet.dart

Today the image preview shows the image in the center of the tab bar. We want to show on top.

fix(image preview): Align image preview on top PE-1484

---

lib/blocs/sync/sync_cubit.dart

UI Crashes and enters an infinite loop on negative blockheights.
For unknown reasons if the query to Arweave for the latest blockheight fails, we could end with a negative blockheight to be used during sync, which crashes the Sync progress UI and leads to an infinite loop.

Fix: Handle negative numbers getting the current block height

---

lib/components/app_drawer/app_drawer.dart

In the bottom left of ArDrive Web is a “Help” button.  It currently points to 
https://ardrive.typeform.com/to/pGeAVvtg 
This link must be updated to point to the new ArDrive Zendesk Help Center
https://ardrive.zendesk.com/

Update help link PE-1560

---

lib/blocs/sync/sync_cubit.dart

Anytime that we try to attach a drive while syncing we'll have unexpected behavior. It can be achieved by following some steps:
1. Log in on ArDrive
2. After sync, choose a public drive of your preference and copy the id
3. Paste this id on app.ardrive.io/#/drives/$driveId
4. It will trigger the sync and the attach at the same time
5. Attach a drive before sync ends
Following those steps, you can see an empty page.
------- 
This PR will cover the following scenario:
For fresh pages, the current delay of 1s to finish the sync bar animation will be sufficient to win the race condition and not attach the drive properly. So, we'll remove those delays.

Fix not properly show an attached public drive contents

---

lib/blocs/drives/drives_cubit.dart

Fixes contents of detached drive remaining on the drive view.
Also fixes the uncaught console error.

PE 1621/select other drive after detach

---

lib/components/app_drawer/app_drawer.dart
lib/l10n/app_en.arb
lib/misc/resources.dart
lib/utils/launch_inferno_rules.dart

Changes:
- Adds a placeholder for the Flame 🔥 icon on its place.
- When the icon is clicked it opens the Inferno Rules.
- There's a tooltip wording: "The Inferno Rewards Program is in full swing! Click here to check out the rules for participation!"
TODO:
- Replace the placeholder with the actual design (surely addressed in another sub-task)

PE-1757: Put the flame icon

---

lib/blocs/feedback_survey/feedback_survey_cubit.dart

The preference was previously set after the second view of the modal: you first clicked "don't remind me again" and nothing happened, then you clicked "Got it" and the flag was set after.
Now the flag is set when clicking the first button.

feat(survey feedback modal): set the pref on dontRemindMe() PE-1773

---

lib/blocs/file_download/file_download_cubit.dart
lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
lib/utils/mime_lookup.dart
lib/utils/upload_plan_utils.dart
test/utils/mime_lookup.dart

Implements a wrapper for the lookupMimeType function to support tar.gz files as well (**already reviewed at** #557).
This is the approach we've decided after noticing that the Dart PR might take some time to be delivered. See the pull request at: https://github.com/dart-lang/mime/pull/66

PE-402: tar.gz files get the wrong content-type

---

lib/blocs/profile/profile_cubit.dart
lib/main.dart
lib/pages/app_router_delegate.dart
test/blocs/feedback_survey_cubit_test.dart

It seemed that there was a crash I didn't have when developing; it was related to a comment regarding #563 (the comment is on [Slack](https://ardrive.slack.com/archives/C01CTS2Q9DM/p1656437774437569?thread_ts=1656433184.207689&cid=C01CTS2Q9DM)).
Also removes an extra await in the tests.
At `lib/pages/app_router_delegate.dart` and `lib/main.dart` you'll find the relevant changes.

PE-1774: Fixes a crash on the ProfileCubit

---

lib/components/app_dialog.dart
lib/components/file_share_dialog.dart

Changes:
- Makes AppDialog to take an extra onWillPopCallback function.
- Pass the callback at the Share Dialog to open the Feedback Modal.

PE-1772: Open Feedback Modal after Share Dialog is dismissed by clicking the screen behind

---

lib/components/app_drawer/app_drawer.dart
lib/components/create_manifest_form.dart
lib/misc/resources.dart
lib/pages/app_route_information_parser.dart
lib/pages/profile_auth/components/profile_auth_add_screen.dart
lib/pages/profile_auth/components/profile_auth_fail_screen.dart
lib/pages/profile_auth/components/profile_auth_loading_screen.dart
lib/pages/profile_auth/components/profile_auth_onboarding_screen.dart
lib/pages/profile_auth/components/profile_auth_prompt_wallet_screen.dart
lib/pages/profile_auth/components/profile_auth_shell.dart
lib/pages/profile_auth/components/profile_auth_unlock_screen.dart
lib/pages/screen_not_supported/screen_not_supported_page.dart
lib/pages/shared_file/shared_file_page.dart
lib/utils/launch_inferno_rules.dart
test/utils/launch_inferno_rules_test.dart

The rules for Inferno are written in English and Chinese, yet the in-app fire icon only directs users to the English rules page. We need to ensure that users of the Chinese version of the app are redirected to the Chinese rules page.

feat: direct inferno icon to chinese rules PE-1808

---

pubspec.yaml

The commit message is incorrect. It is 1.26.2.

chore(app version) use version 1.26.2 PE-2025

---

lib/blocs/sync/sync_cubit.dart
lib/pages/app_router_delegate.dart

Synchronization begins at block 0 after unlocking the session, resulting in a full sync again.
Further incremental syncs work as expected.
After logging back in from a locked state, the drive state should resume synchronizing from the block height where it last left off.

fix: save drive state locally

---

README.md
lib/main.dart
lib/services/config/config_service.dart
lib/utils/key_value_store.dart
lib/utils/local_key_value_store.dart
pubspec.lock
pubspec.yaml
test/blocs/drive_create_cubit_test.dart
test/blocs/folder_create_cubit_test.dart
test/utils/key_value_store_test.dart

Changes
- Uses `LocalKeyValueStore` instead of a cookie to hold the custom URL
- Removes the `cooky` dep
- ~FIXME: Some versions were unintentionally updated~
- Adds an entry to the README.md explaining the new behavior

PE-1919: Refactor custom Arweave Gateway URL

---

lib/pages/drive_detail/components/drive_file_drop_zone.dart

Use `XFile` to validate if the file is not a Folder.

fix(dropzone): validate if the dropped entity is not a folder

---

README.md

Adds missing leading `flutter` command
Adds mention to `export` to path

documentation(typo): Adds missing flutter command

---

lib/blocs/profile_add/profile_add_cubit.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6u9ia4tu10f1g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5adg0amhh2rmo

PE-2471: biometric login enabled from profile, no fingerprint/face id request from lock screen

---

lib/blocs/file_download/file_download_cubit.dart
lib/blocs/file_download/shared_file_download_cubit.dart
lib/components/file_download_dialog.dart
lib/pages/shared_file/shared_file_page.dart
lib/pages/shared_file/shared_file_side_sheet/shared_file_side_sheet.dart

If we access a shared file from a private drive and paste it in a new tab, it is not possible to download any revision of the file from the 'Details' and 'Activity' panel.
Now we are using the `FileRevision` to download the file.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4b2dr4krpceh8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5a2i81bjemppg

PE-2309: fix: previous versions cannot be downloaded in sharing landing page mode

---

pubspec.lock
pubspec.yaml

Some tests were failing due to outdated firebase versions. Upgraded to:
firebase_crashlytics: ^3.0.4
firebase_core: ^2.1.1
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5bnca03ubd7mo

chore: upgrade firebase deps

---

lib/blocs/file_download/personal_file_download_cubit.dart
lib/components/file_download_dialog.dart
test/blocs/personal_file_download_cubit_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/76dcpdu60jjm8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/20gfv4nnk5fp8

PE-2615: ok button doesnt work in modal warning for private files on mobile

---

packages/ardrive_ui_library/lib/src/components.dart
packages/ardrive_ui_library/lib/src/components/button.dart
packages/ardrive_ui_library/lib/src/styles/fonts/typography.dart
packages/ardrive_ui_library/storybook/lib/src/colors.dart
packages/ardrive_ui_library/storybook/lib/src/story_book.dart
packages/ardrive_ui_library/test/src/components/button_test.dart

This PR is from the Theme branch which PR is open: #782. I suggest finishing the review there and then reviewing this.
Adds the `ArDriveButton` component. This component has 3 styles: `primary`, `secondary`, and `tertiary`. It uses the `ArDriveTheme` and also the `Design tokens`.
Primary: 
Secondary:
Tertiary:
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/56ohrs9f91e1g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0pt7e439ei5n0

PE-2559 button component

---

packages/ardrive_ui_library/lib/src/components.dart
packages/ardrive_ui_library/lib/src/components/card.dart
packages/ardrive_ui_library/lib/src/styles.dart
packages/ardrive_ui_library/lib/src/styles/colors/global_colors.dart
packages/ardrive_ui_library/lib/src/styles/colors/sematic_colors.dart
packages/ardrive_ui_library/lib/src/styles/shadows/shadows.dart
packages/ardrive_ui_library/lib/src/styles/theme/themes.dart
packages/ardrive_ui_library/storybook/lib/src/button.dart
packages/ardrive_ui_library/storybook/lib/src/card.dart
packages/ardrive_ui_library/storybook/lib/src/colors.dart
packages/ardrive_ui_library/storybook/lib/src/shadows.dart
packages/ardrive_ui_library/storybook/lib/src/story_book.dart
packages/ardrive_ui_library/storybook/lib/src/toggle.dart
packages/ardrive_ui_library/test/src/components/card_test.dart

Adds the `ArDriveCard` component. This component is the basic `Card` component.
Adds the `ArDriveShadows` design tokens and some missing Colors.
Examples in the Storybook - Widgetbook:
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4jfafkpu3soa8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2mc65847a2d3g

PE-2570: add card component

---

lib/blocs/sync/sync_cubit.dart
lib/blocs/sync/utils/parse_drive_transactions.dart
lib/blocs/sync/utils/sync_drive.dart
lib/services/arweave/arweave_service.dart
lib/utils/snapshots/drive_history_composite.dart
lib/utils/snapshots/range.dart
lib/utils/snapshots/snapshot_drive_history.dart
lib/utils/snapshots/snapshot_item.dart
test/services/arweave/arweave_service_test.dart
test/utils/drive_history_composite_test.dart
test/utils/gql_drive_history_test.dart
test/utils/range_test.dart
test/utils/snapshot_drive_history_test.dart
test/utils/snapshot_item_test.dart
test/utils/snapshot_test_helpers.dart

Changes
- Instantiates the components for reading GQL Nodes from snapshots
- Replaces the source stream of GQL data with the Quick Sync one
- Consumes the data from SnapshotItem before going to the network
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7masfamcitlj0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5uriaae91bps8

PE-2632: Make use of the components for Quick Sync [Read-side]

---

lib/entities/constants.dart
lib/utils/snapshots/snapshot_item.dart
lib/utils/snapshots/snapshot_item_to_be_created.dart
test/utils/drive_history_composite_test.dart
test/utils/snapshot_drive_history_test.dart
test/utils/snapshot_item_test.dart
test/utils/snapshot_item_to_be_created_test.dart
test/utils/snapshot_test_helpers.dart

Changes
- Makes SnapshotItemToBeCreated to no longer extend SnapshotItem
- SnapshotItemToBeCreated has the responsibility of knowing the data of the snapshot
- Updates the tests for SnapshotItem
- Implements the tests for SnapshotItemToBeCreated
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2s12d12f3cj40
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5qb0i8mp9dbp0

PE-2814: Snapshot to be created

---

lib/models/tables/all.drift
lib/models/tables/snapshot_entries.drift

Changes
- Declares a new table for Snapshot Entries: It tracks:
- The snapshot id,
- the drive id,
- the block range and
- the data range, and
- the unix time.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3kp3nbad076o8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2k58hof0rt4h0

PE-2824: creates a table for SnapshotEntry

---

android/fastlane/metadata/android/en-US/changelogs/18.txt
lib/models/tables/all.drift
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3e7caao7oljeo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4qj9mmm3i5sl0

PE-2875: removes the import of snapshot entries

---

lib/services/arweave/arweave_service.dart

Since a new Entity-Type was added, the sync process wasn't ready to handle these. Now, the sync process will ignore "unknown" (or "yet unimplemented") entities.
**Changes**
- Ignore unknown ArFS entities 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7hvussu7ths8g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2q28gqhpss74g

PE-2929: feat(sync drive) ignore unknown entities

---

lib/blocs/create_snapshot/create_snapshot_cubit.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/703mhl64q0flo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1jklhai1m1ldo

PE-2969: fixes edge case where failure event wasn't emitted 

---

android/fastlane/metadata/android/en-US/changelogs/21.txt
android/fastlane/metadata/android/en-US/changelogs/22.txt
assets/config/prod.json
pubspec.yaml

Changes
- Version bump 
- Re enables quick sync authoring feature flag
- Puts Android release notes
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/70b1c05g1ntsg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/03cmbgkld51oo

PE-2941: re-enables quick sync authoring

---

lib/entities/snapshot_entity.dart

Fixes broken test on #850 - This change doesn't affect the way SnapshotEntities deals with encryption (it doesn't use encryption since the data for private drives will be already encrypted).
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1ilt8udj3d9p8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1ar55s6il9hug

PE-2583: feat(snapshot entity): fixes broken test after integrating dev

---

lib/components/app_dialog.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0m0oqo7jkimt8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/593qcop9q4ocg

PE-2981: Makes the AppDialog title to wrap on overflow 

---

lib/blocs/create_manifest/create_manifest_cubit.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2pg4pj2mgneo8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/087p1b2ehegm0

PE-3109: fix - add size check before using turbo for manifests

---

android/fastlane/metadata/android/en-US/changelogs/28.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2gkmpr4fhj6mg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/74f5tnp8h3muo

PE-3220: chore: bump version

---

lib/blocs/create_snapshot/create_snapshot_cubit.dart
lib/blocs/sync/sync_cubit.dart
lib/services/arconnect/is_document_focused.dart
lib/utils/html/html_util.dart
lib/utils/html/implementations/html_stub.dart
lib/utils/html/implementations/html_web.dart
test/blocs/create_snapshot_cubit_test.dart
web/index.html
web/js/is_document_focused.js

Changes:
1. Renames `isTabFocused` into `isTabVisible`
2. Implements `isTabFocused` for web only, based on the `document.hasFocus` method in JavaScript.
3. Refactors the call to `arconnectSync` to call the new `isTabFocused` instead of the old one (now called `isTabVisible`)
**Note** See "Quickened arconnect sync" for testing/QA: #973
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6pjp7e9i70vh0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6fd6p4m1h3kvo

PE-3132: ArConnect logout MVP

---

lib/components/details_panel.dart
lib/components/file_download_dialog.dart
pubspec.lock
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/16aoapp217vf8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/64eujjda66sa0

PE-3421: no button to close details activity panel

---

lib/blocs/create_snapshot/create_snapshot_cubit.dart
lib/blocs/sync/sync_cubit.dart
lib/blocs/sync/utils/parse_drive_transactions.dart
lib/blocs/sync/utils/sync_drive.dart
lib/services/arweave/arweave_service.dart
lib/services/arweave/graphql/queries/DriveEntityHistory.graphql
lib/services/arweave/graphql/queries/SnapshotEntityHistory.graphql
lib/utils/snapshots/gql_drive_history.dart
test/blocs/create_snapshot_cubit_test.dart
test/services/arweave/arweave_service_test.dart
test/utils/drive_history_composite_test.dart
test/utils/gql_drive_history_test.dart

Changes
- Makes `DriveEntityHistory` and `SnapshotEntityHistory` queries to take the owner address.
- Refactors the callees to have the address injected into those.
- For snapshot creation it comes from the logged in profile
- For sync it comes from the DriveDao
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7e9qf7is7vogo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/555fgqh9pkid8

PE-3352: Adds the `owners` field to the GQL queries

---

lib/utils/html/implementations/html_web.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0lrqfkc2en3pg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1m6j5lg2qn440

PE-3396: replaces in the implementation document.onFocus with window.onFocus

---

lib/blocs/create_snapshot/create_snapshot_cubit.dart
lib/utils/html/html_util.dart
lib/utils/html/implementations/html_web.dart
test/blocs/create_snapshot_cubit_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/687dl69g9tib8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4pve58qndokjo

PE-3566: Sign and prepare phase of snapshot creation throws an error when back on focus

---

lib/components/details_panel.dart
lib/pages/drive_detail/components/drive_explorer_item_tile.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/683116sttmgm0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/2sphkldk702to

PE-3589: fix(preview button): remove preview button for private drives

---

lib/blocs/create_manifest/create_manifest_cubit.dart
lib/blocs/drive_create/drive_create_cubit.dart
lib/blocs/folder_create/folder_create_cubit.dart
lib/blocs/fs_entry_move/fs_entry_move_bloc.dart
lib/blocs/fs_entry_rename/fs_entry_rename_cubit.dart
lib/blocs/ghost_fixer/ghost_fixer_cubit.dart
lib/blocs/sync/utils/add_drive_entity_revisions.dart
lib/blocs/sync/utils/add_file_entity_revisions.dart
lib/blocs/sync/utils/add_folder_entity_revisions.dart
lib/blocs/sync/utils/parse_drive_transactions.dart
lib/blocs/upload/upload_handles/file_data_item_upload_handle.dart
lib/blocs/upload/upload_handles/file_v2_upload_handle.dart
lib/blocs/upload/upload_handles/folder_data_item_upload_handle.dart
lib/entities/custom_metadata.dart
lib/entities/drive_entity.dart
lib/entities/file_entity.dart
lib/entities/folder_entity.dart
lib/models/file_revision.dart
lib/models/folder_revision.dart
lib/services/arweave/arweave_service.dart
test/entities/custom_metadata.dart
test/entities/custom_metadata_test.dart

Changes
- Adds to drive, folder, and file entities the customJsonMetaData field
- Sets the value ONLY at sync time - For creation/rename/move and any other operation, it's not being set
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5v4k4e780i600
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5osi9ig195g98

PE-3581: Write custom metadata while syncing

---

web/js/arconnect.js

Changes
- Passes the favicon URL to ArConnect as the app `logo` through the `appInfo` parameter of the `connect` method.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7dt0luggs7jjo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4ughg5igova10

PE-2903: Update ArDrive Icon in ArConnect

---

lib/authentication/login/views/login_page.dart
lib/components/create_manifest_form.dart
lib/misc/resources.dart

Changes
- Adds the link to the resources file
- Puts the "Learn More" link in the tooltip
Free win:
- Fixes the missing space for the Manifest Explanation
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2uoa5lq56tkl0
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/1lm7ulgtisks0

PE-3762: Add Keyfile Login "Learn More" Link

---

android/fastlane/metadata/android/en-US/changelogs/45.txt
pubspec.yaml

Changes
- Android release notes (next prod deploy number is 45)
- App version bump
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1fue73b2crtdo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/14oalufdvedho

PE-3977: Before-release preparations

---

lib/components/top_up_dialog.dart
lib/turbo/topup/blocs/topup_estimation_bloc.dart
lib/turbo/topup/blocs/topup_estimation_state.dart
test/turbo/blocs/topup_estimation_bloc_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1gr8f6acuo998
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/7gsjr95og93r0

PE-4005: retains previous amount instead of displaying newly selected amount

---

lib/components/details_panel.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7051kman9fh2o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5ipjj47s7j0d8

PE-4030: fix: use metadata tx id on details panel

---

lib/services/turbo/payment_service.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1v05ontk8nns8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/39elmhvui4vig

PE-4051: fix(turbo + arconnect): use getOwner instead of publicKey with RSA

---

lib/core/upload/uploader.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0bravu0cj5dpo
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5s5fsacidooi8

PE-4203: fix(turbo upload sizes): fix logic to display turbo sizes

---

lib/components/top_up_dialog.dart
lib/components/upload_form.dart
lib/l10n/app_en.arb

Update receipt text to, “To receive a receipt, please provide an email.”
Update empty field error to, “Field required”
Change “ArDrive Credits” to “Credits” on turbo top up
Missing colon. Both should say “Cost:” but the “:” is missing from the Credit option
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5bf0m5vs1ee7g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/6d99446vm4hro

PE-4157: update texts on top up and upload form

---

lib/blocs/profile/profile_cubit.dart
lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_handles/bundle_upload_handle.dart
lib/core/arconnect/safe_arconnect_action.dart
lib/core/upload/bundle_signer.dart
lib/core/upload/transaction_signer.dart
lib/main.dart
lib/services/turbo/upload_service.dart

TODO - we have to cleanup html_utils.dart in order to avoid this kind of confusion: we cannot use the JS implementations directly in the code because they will throw in non-JS platforms.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6dq855tgj7v1g
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/086ubcdd5qfbg

PE-4173: inject tab visibility

---

lib/components/top_up_dialog.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/17u6jn0cd85r8
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/4jq38kq3v1e2g

PE-4228: change equal symbol to estimate symbol

---

lib/l10n/app_en.arb

Translations also updated in Localizely
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/54c37bn81sotg
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5nd7ma2enkdj8

PE-4230: capitalize credits word

---

lib/l10n/app_en.arb
lib/l10n/app_zh-HK.arb

Exported the most recent translations from Localizely
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2le7flvq1ulco
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0h3qfoe4cnieg

PE-4225: Change wording for the "session expired" message of turbo top-up

---

lib/blocs/sync/sync_cubit.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/32qt7hjb4qr9o
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/5dfkimroigr78

PE-4226: Too frequent syncs are triggered for a wallet with no drives

---

android/fastlane/metadata/android/en-US/changelogs/52.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3cnta7vo77428
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/21307k47r7l8o

PE-4274: bump version and android release notes

---

lib/authentication/ardrive_auth.dart
lib/authentication/login/blocs/login_bloc.dart
test/authentication/ardrive_auth_test.dart
test/authentication/login/blocs/login_bloc_test.dart

- implements `userHasPassword` method to verify if the user has created at least a single private drive.
- Shows the onboarding if the user has drives or not but no private drives
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/190rpfkooohdg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0b70saavbvnfg

PE-4275: fixes the issue when the unlock page is displayed when the user has only public drives

---

lib/turbo/topup/views/topup_review_view.dart
pubspec.lock
pubspec.yaml

- use `titleWidget` on checkbox at the review page
- use fixed version of ardrive_ui
https://github.com/ardriveapp/ardrive-web/assets/32248947/f726a31d-6991-4b45-8ab8-5ddabae0491a
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/64m3kltsufs8g

PE-4243: Replicate checkbox line functionality on review page

---

lib/components/new_button/new_button.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6hh134cc8hrko

PE-4359: Disable option for pin, snapshot and manifest if drive is readonly

---

android/fastlane/metadata/android/en-US/changelogs/54.txt
pubspec.lock
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3gmpnak9t3egg

PE-4499: pre-release tasks v2.8.0

---

lib/services/arweave/arweave_service.dart
lib/services/arweave/graphql/queries/UserDriveEntities.graphql

I encountered we're requesting a maximum of 100 individual drives (perhaps intended). This PR removes that limit.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/28u73hu6uvk80

PE-4502: makes UserDriveEntities query use pagination

---

lib/blocs/file_download/file_download_state.dart
lib/blocs/upload/limits.dart
lib/download/limits.dart
lib/download/multiple_download_bloc.dart
lib/download/multiple_download_event.dart
lib/download/multiple_download_state.dart
lib/download/multiple_file_download_modal.dart
lib/pages/drive_detail/drive_detail_page.dart
lib/utils/app_platform.dart
pubspec.yaml
test/blocs/personal_file_download_cubit_test.dart
test/download/limits_test.dart
test/download/multiple_download_bloc_test.dart
test/test_utils/mocks.dart

Implements multi-file downloading for files on public and private drives with ability to skip, retry, and cancel in download error scenarios. 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/13kdqniv14mag

PE-4420: implement-multiple-downloads-for-files

---

lib/blocs/file_download/file_download_cubit.dart
lib/blocs/file_download/personal_file_download_cubit.dart
lib/core/download_service.dart
lib/download/download_utils.dart
lib/download/multiple_download_bloc.dart
test/blocs/personal_file_download_cubit_test.dart
test/download/multiple_download_bloc_test.dart

adds support for downloading manifest files from raw endpoint
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7h435u8p0sf6o

PE-4412: unable-to-download-manifest-file-items

---

lib/blocs/drive_create/drive_create_cubit.dart
lib/blocs/drive_create/drive_create_state.dart
lib/components/drive_create_form.dart
test/blocs/drive_create_cubit_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5uboc4dgpe1a0

PE-4632: Persistent loading issue when creating drives

---

lib/blocs/drive_create/drive_create_cubit.dart
lib/blocs/drive_create/drive_create_state.dart
lib/components/drive_create_form.dart
lib/l10n/app_en.arb
test/blocs/drive_create_cubit_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ujc5gdo66s6o

PE-4597: adds a description of the selected drive privacy

---

lib/pages/drive_detail/drive_detail_page.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5gc4p0o7dh7oo

PE-4650: Missing 'Detach Drive' option on Android and Mobile WebView

---

assets/config/dev.json
assets/config/prod.json
assets/config/staging.json
lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
lib/blocs/fs_entry_preview/fs_entry_preview_state.dart
lib/dev_tools/app_dev_tools.dart
lib/l10n/app_en.arb
lib/pages/drive_detail/components/fs_entry_preview_widget.dart
lib/pages/drive_detail/drive_detail_page.dart
lib/services/config/app_config.dart
lib/utils/constants.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

Implements audio media player for public audio files.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4q0odpibmp6i0

PE-4582: Audio Preview

---

lib/blocs/create_snapshot/create_snapshot_cubit.dart
lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/create_snapshot_dialog.dart
lib/components/payment_method_selector_widget.dart
lib/components/upload_form.dart

- Adds the insufficient balance message for snapshot creation.
- Makes it not to be shown when free turbo uploads (same for file upload).
- Makes the insufficient message for Turbo be displayed in the File Upload modal.
- Makes the button be accordingly enabled/disabled.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2hrepjq4mrcd0

PE-4676: Issues around the balance for snapshot creation

---

lib/components/create_snapshot_dialog.dart

Uses showModalDialog to mark add snapshot dialog as uninterruptible. 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7rhvrgren52qg

PE-3953: sync-can-happen-in-background-when-creating-a-snapshot

---

lib/authentication/login/views/login_page.dart
lib/components/app_version_widget.dart
lib/components/side_bar.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/33p4auvocj9u8

PE-4533: Add Version Number to Login Screen

---

lib/blocs/file_share/file_share_cubit.dart
lib/blocs/file_share/file_share_state.dart
lib/components/file_share_dialog.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/790aqo2pk0mjo

PE-4081: feat(share file): allow to share file when the file is pending

---

lib/pages/drive_detail/components/drive_explorer_item_tile.dart
lib/pages/drive_detail/drive_detail_page.dart
lib/turbo/topup/views/topup_payment_form.dart
pubspec.lock
pubspec.yaml

- Makes the dropdown overlay match the with of the field.
- Moves the field just below the Credit Card one.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/64pc2mpg6a7no

PE-4397: Country Dropdown - Fixes

---

lib/blocs/create_snapshot/create_snapshot_cubit.dart
lib/components/create_snapshot_dialog.dart
lib/dev_tools/app_dev_tools.dart
lib/services/config/app_config.dart
lib/services/config/config_service.dart
lib/turbo/topup/blocs/payment_review/payment_review_bloc.dart
lib/turbo/topup/blocs/payment_review/payment_review_event.dart
lib/turbo/topup/views/topup_modal.dart
lib/turbo/topup/views/topup_review_view.dart
lib/turbo/turbo.dart
pubspec.lock
pubspec.yaml
test/blocs/create_snapshot_cubit_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0bgop1j6s3fq8

PE-4694: Credit update issue during snapshot creation purchase

---

lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart
lib/l10n/app_en.arb
lib/pages/drive_detail/components/fs_entry_preview_widget.dart
lib/utils/constants.dart

* Redesigned to accept all video mime types, but show error if format is unsupported by underlying video player
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5ov25e60c7a2o

PE-4732: video-preview-doesnt-accept-all-mov-and-mpg-formats

---

lib/turbo/services/payment_service.dart
lib/turbo/topup/blocs/payment_form/payment_form_bloc.dart
lib/turbo/topup/blocs/payment_form/payment_form_state.dart
lib/turbo/topup/blocs/topup_estimation_bloc.dart
lib/turbo/topup/models/payment_model.dart
lib/turbo/topup/models/price_estimate.dart
lib/turbo/topup/views/topup_payment_form.dart

Follow-up work of #1349 - See the open comments in @thiagocarvalhodev's review.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/51pkhnuc5rnto

PE-4565: Address the tech debt created by Turbo Promo Code

---

lib/services/ethereum/provider/implementations/ethereum_provider_web.dart

This improves compatibility with some other wallets (e.g. Phantom)

Request credentials before switching chain.

---

lib/pages/drive_detail/components/fs_entry_preview_widget.dart

Changes video player popup to show 'Normal' in the same way as implemented as Audio Player. 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7bn0281d665h0

PE-4778: missing-normal-playback-option-video-preview

---

lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/upload_form.dart
packages/ardrive_uploader/lib/src/d2n_streamed_upload.dart
packages/ardrive_uploader/lib/src/turbo_streamed_upload.dart
packages/ardrive_uploader/lib/src/turbo_upload_service_dart_io.dart
packages/ardrive_uploader/lib/src/turbo_upload_service_web.dart
packages/ardrive_uploader/lib/src/upload_controller.dart
packages/ardrive_uploader/pubspec.yaml
pubspec.lock
pubspec.yaml

Implements the ability to cancel a D2N upload. We are also providing a warning to the user that he can lose his money while canceling an in-progress upload.
For Turbo uploads, it doesn't change the current behavior.
https://github.com/ardriveapp/ardrive-web/assets/32248947/283b7b16-b574-43e5-b0ba-640788416fc2
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7mmpmj5ovaar8

PE-4812: cancel button fails to stop file upload when using ARs only

---

lib/blocs/upload/limits.dart
lib/blocs/upload/models/upload_plan.dart
lib/blocs/upload/upload_cubit.dart
lib/core/upload/uploader.dart
lib/utils/upload_plan_utils.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/41hn6ks5ic188

PE-4808: makes turbo uploads be marked as not possible when size is below the limit

---

lib/blocs/upload/upload_cubit.dart
packages/ardrive_uploader/lib/src/data_bundler.dart
pubspec.lock

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/34v7mko985eso

PE-4864: fix upload warning

---

lib/blocs/file_download/file_download_cubit.dart
lib/blocs/file_download/shared_file_download_cubit.dart
lib/components/file_download_dialog.dart

implement the new downloader on the shared page
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5mdd8e2u4dmc8

PE-4885: use new downloader on share file page

---

lib/pages/drive_detail/components/fs_entry_preview_widget.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5b4r0usi4sbfo

PE-4928: Corrects the duplicate time indicators for video preview in drive explorer

---

lib/components/details_panel.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0o6d959ghr0kg

PE-4842: wrap text on details panel when values are huge

---

lib/components/details_panel.dart
lib/misc/resources.dart
lib/pages/shared_file/shared_file_page.dart

Adds the app version to the details panel (only on the share page)
---
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7q0pf7a1tmiao

PE-4907: add Version to Share Page

---

lib/download/ardrive_downloader.dart

- use the `decryptTransactionData` instead of `decryptTransactionDataStream` method to decrypt the file on Dart VM (Mobile).
Using the `decryptTransactionDataStream` we get the following exception: 
```
Error saving file: 'package:webcrypto/src/impl_ffi/impl_ffi.aesctr.dart': Failed assertion: line 155 pos 16: 'i == M': is not true.
```
Note that it seems to use the aes ctr even passing the right cipher: **GCM**.
For now, we are using the old method (current in prod) to decrypt the file using GCM.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5c7rp53c6c740

PE-5087: download modal stays open in android for private files

---

lib/blocs/fs_entry_preview/fs_entry_preview_cubit.dart

* Added missing emit of FsEntryPreviewUnavailable() for condition when file.size > previewMaxFileSize
* Added additional initial emitting of FsEntryPreviewUnavailable() as a starting state, since the determination of preview type is done async. This reduces the flickering of tabs when going to items that do not have preview (would show a tab then quickly remove it). 
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4ib7rc0rgc8lg

PE-5017: Fix Preview Panel showing for private files larger than previewMaxFileSize

---

lib/components/details_panel.dart
lib/pages/drive_detail/components/fs_entry_preview_widget.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5kvce6ep4n0tg

PE-5212: fix file name shirking preview

---

lib/components/fs_entry_license_form.dart

Add scrollbar to License configuring/reviewing screens. This fixes visibility of back/next buttons on mobile chrome (or very tiny android screens?)

Fix licensing config/review screen on small displays

---

lib/pages/drive_detail/components/drive_explorer_item_tile.dart
pubspec.lock
pubspec.yaml

- set content type to lower case for getting the right icon
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/59otoa42nu1g8

PE-5431: show appropriate icon on upload page for file with extension written in uppercase

---

lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
lib/components/license_summary.dart

- Details: Prefer `FileRevision`/`LicenseState` from App DB, even for Shared Files
- Details: Fall back to "Pending" License when licenseTxId is present in Latest Revision, but not mined or in DB
- LicensePopover will not show the "View" link for "unknown" type Licenses

Fixes for Shared File Page

---

lib/blocs/prompt_to_snapshot/prompt_to_snapshot_bloc.dart
lib/blocs/prompt_to_snapshot/prompt_to_snapshot_event.dart
lib/components/prompt_to_snapshot_dialog.dart

- add event for when the modal is closed
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6s0ek01uv25lo

PE-5457: modal doesnt reappear after closing with x

---

packages/ardrive_uploader/lib/src/upload_controller.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3c6j9g6ntkh7g

PE-5474: fix missing cipher and cipherIv tags for Turbo uploads

---

android/fastlane/metadata/android/en-US/changelogs/90.txt
pubspec.yaml

- Fixes missing ciphering tags on private uploads to Turbo
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0e42bjfeiqrbo

PE-5440: Release ArDrive App v2.30.2

---

lib/blocs/drive_detail/drive_detail_cubit.dart

For large folders, we perform huge computational tasks renaming and generating the fs entry paths. This triggers the DriveDetailCubit to rebuild lots of times, it is not tooooo expensive, because it won't rebuilt the datatable those hundreds of times. But, it leads an issue where the state is emitted before the UI gets updated. The UI won't have the new state and then won't update the drive explorer.
This delay fixes it. Some refs: 
https://stackoverflow.com/questions/64370986/blocbuilder-not-updating-after-cubit-emit, https://github.com/felangel/bloc/issues/2094
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3ogaotkkbce70

PE-5461: renaming folder still doesnt update instantly

---

lib/sharing/folder_selector/folder_selector.dart
lib/sharing/folder_selector/folder_selector_bloc.dart
lib/sharing/folder_selector/folder_selector_event.dart
lib/sharing/folder_selector/folder_selector_state.dart
lib/sharing/sharing_file_listener.dart

- enhance the folder selector widget: now you can navigate the folder tree, instead of just listing all folders
- update activity tracker properly when closing the select folder modal
- UI now gets updated when the upload finishes
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/6ihvm24sd76p8

PE-5498: duplicate public drives and uncreated folders

---

lib/blocs/sync/sync_cubit.dart
lib/core/activity_tracker.dart
lib/sharing/blocs/sharing_file_bloc.dart
lib/sharing/folder_selector/folder_selector.dart
lib/sharing/sharing_file_listener.dart
pubspec.lock
pubspec.yaml

- use a fixed version of the sharing intent plugin.
https://github.com/bhagat-techind/flutter_sharing_intent/pull/51
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2nl9m5ui9qu4g

PE-5521: missing modal for txt files

---

lib/sharing/blocs/sharing_file_bloc.dart

only initialize the sharing intent if running on mobile
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5bllmrhlbb6c0

PE-5544: update sharing_file_bloc.dart

---

lib/main.dart
lib/pages/drive_detail/drive_detail_page.dart

- Adds the SafeArea widget on top of the drive detail page
- Now the bottom bar won't be displayed when the keyboard is appearing, for example, when renaming a file. That's the change with the `resizeToAvoidBottomInsets` to `false`
------ 
https://github.com/ardriveapp/ardrive-web/assets/32248947/bfd32a10-beb3-4ba2-ad04-ef586c7b8f46
https://github.com/ardriveapp/ardrive-web/assets/32248947/7e2805ce-92fe-41c5-8717-7a38e1fd3204
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/62b57dnipqihg

PE-5598: viewport is cutoff by bottom navigation bar

---

lib/core/upload/uploader.dart

if it's free, set turbo as the default option
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/17ei90jiq9l0o

PE-5635: fix free uploads when payment service is down

---

assets/config/dev.json
assets/config/prod.json
assets/config/staging.json
lib/core/upload/uploader.dart

* modifies config values that control turbo free size limit check to match new values from turbo service
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4tfsedf452sm0

PE-5662: reduce turbo free file size limit check to match service

---

.github/workflows/production.yaml
pubspec.yaml

- disables production android build
- bump version
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4uje6i4q58i0g

PE-5697: chore(bump version and android build)

---

lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
lib/blocs/fs_entry_license/fs_entry_license_bloc.dart
lib/components/details_panel.dart
lib/components/fs_entry_license_form.dart
lib/entities/license_assertion.dart
lib/services/license/license_service.dart
lib/services/license/license_state.dart
lib/services/license/licenses/cc_by.dart
lib/services/license/licenses/udl.dart
test/services/license/license_state_test.dart

We've added a variety of CC licenses to offer a broader range of sharing permissions. The new licenses include:
- CC0 (Public Domain Dedication)
- CC-BY (Attribution)
- CC-BY-NC (Attribution-NonCommercial)
- CC-BY-NC-ND (Attribution-NonCommercial-NoDerivs)
- CC-BY-NC-SA (Attribution-NonCommercial-ShareAlike)
- CC-BY-ND (Attribution-NoDerivs)
- CC-BY-SA (Attribution-ShareAlike)
- Removed Unused Property: The version property of `LicenseMeta` 
- Introduced LicenseCategory Enum
- We have updated the versioning for both UDL and CC-BY licenses. The UDL license is now at version 0.2, reflecting recent enhancements.
- additionally, we've incorporated a new transaction for the CC-BY 4.0 license
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030: …

PE-5690: feat(ANS-105) adds new cc license types

---

lib/components/upload_form.dart
lib/models/forms/cc.dart

Changes
- Factor out shared form / logic / UI between FsEntryLicence & to share with Upload
- FsEntryLicence
- Be more explicit about using `LicenseCategory`
- Fix inconsistent behaviour of back button in FsEntryLicence review screen - now it returns to the previous screen for all CC licenses
- Fix sometimes using v0.1 of UDL license instead of v0.2
- Upload UI
- Added dropdown to select `LicenseCategory`
- Added screen to configure selected `LicenseCategory`
- Added Review screen (only for when license is configured)
- modified `_uploadUsing*Uploader` functions to accept the configured License
- Misc naming fixes
- Misc DRY

License on upload

---

lib/utils/snapshots/snapshot_item_to_be_created.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/10m1hgpvc1jf0

PE-5843: (Firefox) fix snapshot creation on huge drives by fetching entities using a batching strategy

---

lib/services/arweave/graphql/queries/FirstTxForWallet.graphql

fixes gql query to sort before grabbing first tx
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/2quaf5b8r9tng

PE-5897: meta-mask-authentication-error-due-to-graph-ql-transaction-retrieval-issue

---

lib/turbo/services/payment_service.dart

- TurboUserNotFound exception implements now the UntrackedException

PE-5899: Dont log `TurboUserNotFound` on Sentry

---

lib/components/details_panel.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1h1sg7sgsl328

PE-6136: null error null check operator used on a null value overlay remove error

---

lib/services/arweave/arweave_service.dart

`EntityTransactionParseException` is an `UntrackedException`. We don't need to log as `e` since we won't log it.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7f5ipihmea9j8

PE-6140: don't log `EntityTransactionParseException`

---

lib/pages/drive_detail/drive_detail_page.dart

add create snapshot to drive options on desktop and mobile
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0seq0a0o61fr8

PE-6375: add create snapshot to drive options on desktop and mobile

---

android/fastlane/metadata/android/en-US/changelogs/140.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0u3veu5u4hkng

PE-6456: chore: bump version and release notes

---

lib/services/arweave/arweave_service.dart
lib/services/arweave/arweave_service_exception.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1807onkvbh2c0

PE-6470: better handling on the get pending tx fees method for null error null check operator used on a null value

---

android/fastlane/metadata/android/en-US/changelogs/145.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/056hf7pdke578

PE-6570: bump version and release notes

---

android/fastlane/metadata/android/en-US/changelogs/146.txt
lib/services/arweave/graphql/queries/FirstDriveEntityWithIdOwner.graphql
pubspec.yaml

~hotfix: remove drive-privacy tag that causes a timeout on attach drive query~
That's not a hotfix, but the Drive-Privacy filter makes the query slower.

PE-6633: fix(attach drives): remove Drive-Privacy filter

---

lib/arns/domain/arns_repository.dart
lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/upload_form.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4l9pl6jssh62g

PE-6730: Decouple arns loading from the main upload flow

---

lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/upload_form.dart

- use size of the files instead of the data items being uploaded
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5j8grleft46vg

PE-6777: feat(upload): display original file sizes on the upload modal

---

lib/authentication/login/views/wallet_created_view.dart

removes `ClipRect` that causes the entire container not to display
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7osmm7v8o0e40

fix seedphrase blur issue

---

lib/blocs/upload/upload_cubit.dart
lib/blocs/upload/upload_state.dart
lib/components/upload_form.dart
packages/ardrive_ui/lib/src/components/check_box.dart
test/blocs/upload_cubit_test.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5dpm65eulf70o

PE-6896: incorrect modal display during file upload process

---

android/fastlane/metadata/android/en-US/changelogs/158.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1v9mbt71g3r98

PE-6900: bump version and release notes

---

lib/app_shell.dart
lib/authentication/ardrive_auth.dart
lib/blocs/drive_detail/drive_detail_cubit.dart
lib/blocs/hide/hide_bloc.dart
lib/models/drive_revision.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4r7tkt7g66soo

PE-7037: missing hide show hidden items icon on android

---

lib/services/arweave/arweave_service.dart
lib/services/arweave/graphql/queries/LicenseDataBundled.graphql

- remove NEQ operator and filter the licenses in the client
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/365f5pn687obo

PE-7153: fix license sync

---

packages/ardrive_uploader/lib/src/exceptions.dart
packages/ardrive_uploader/lib/src/factories.dart
packages/ardrive_uploader/lib/src/turbo_upload_service.dart
packages/ardrive_uploader/lib/src/upload_strategy.dart
packages/ardrive_uploader/test/factories_test.dart

Only use multipart endpoint for uploads larger or equal to 5MB
- Implements the `TurboUploadServiceBase` abstracting the common logic between the chunked and multipart uploads
- use multipart endpoint for files larger or equal to 5MB
- updates unit tests
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/02g4p7rckghog

PE-7256: feat(turbo upload service): Only use multipart endpoint for uploads larger or equal to 5MB

---

lib/blocs/create_manifest/create_manifest_cubit.dart
lib/blocs/upload/upload_cubit.dart
lib/components/details_panel.dart
lib/entities/file_entity.dart
lib/manifest/domain/manifest_repository.dart
lib/models/daos/drive_dao/drive_dao.dart
lib/models/database/database.dart
lib/models/file_entry.dart
lib/models/file_revision.dart
lib/models/tables/file_entries.drift
lib/models/tables/file_revisions.drift
lib/pages/drive_detail/models/data_table_item.dart
packages/ardrive_uploader/lib/src/arfs_upload_metadata.dart
packages/ardrive_uploader/lib/src/metadata_generator.dart

- add fallbackTxId to manifest's metadata
- reuse the fallbackTxId when auto-updating a manifest if the previous has one
- add fallbackTxId property on the FileEntry and FileRevision objects
- migrate the database
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/4n1gd3ra46tv0

PE-7394: fallback tx id not displayed after updating manifest

---

lib/blocs/file_download/personal_file_download_cubit.dart
lib/drive_explorer/thumbnail/repository/thumbnail_repository.dart
lib/drive_explorer/thumbnail_creation/bloc/thumbnail_creation_bloc.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3ci6drlet4458

PE-7399: catch error on device info and add logs on the thumbnail creation flow

---

android/fastlane/metadata/android/en-US/changelogs/174.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1d7a5oat4ps30

PE-7542: chore: bump version and release notes

---

lib/blocs/file_download/personal_file_download_cubit.dart
lib/blocs/file_download/shared_file_download_cubit.dart
lib/download/ardrive_downloader.dart

- Add detailed context to error messages in personal_file_download_cubit.dart including file ID, txId, and gateway URL
- Improve error messages in shared_file_download_cubit.dart with file metadata for better debugging
- Format error messages to include relevant file information directly in the message string
- Ensure consistent error logging pattern across download components
- Add missing catchError handler in ardrive_downloader.dart
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/0ngbbuoo8sevg

PE-5605: logging(download) enhance error handling and logging for file downloads

---

lib/services/arweave/arweave_service.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/49ujirg2asl4g

PE-7826: fix(sync) use `/info` endpoint to get the current block height

---

lib/components/details_panel.dart
lib/pages/drive_detail/components/drive_explorer_item_tile.dart

- Added AppPlatform.isWeb() conditional checks to hide ArNS name assignment in context menus
- Added conditional check in details panel to only show ArNS assignment button on web
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5vqabvrkndca8

PE-6990: fix(arns mobile) hide ArNS name assignment on mobile platforms

---

lib/authentication/ardrive_auth.dart
lib/authentication/login/blocs/login_bloc.dart
lib/authentication/login/blocs/login_state.dart
lib/authentication/login/views/login_page.dart
lib/authentication/login/views/modals/enter_your_password_modal.dart
lib/services/arweave/arweave_service.dart

- add proper error handling when private drive transaction is not found during login
- add new PrivateDriveNotFoundException and TransactionNotFound exceptions
- show user-friendly error message when private drive is still processing
- add additional logging in drive detail cubit and drive dao for better debugging
- improve error handling in arweave service for transaction fetching
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/35b30u4l8pkmg

PE-7836: fix(login) improve login error handling for private drive verification

---

lib/pages/no_drives/no_drives_page.dart

- Add SyncButton to desktop layout in top row of buttons
- Utilize existing SyncButton in MobileAppBar for mobile layout
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/3hq3u46thv3a8

PE-7848: feat(drive explorer) add sync button to no drives page

---

lib/blocs/drive_attach/drive_attach_cubit.dart
lib/components/drive_attach_form.dart

- add mounted checks in DriveAttachForm to prevent state updates after unmount
- add isClosed checks in DriveAttachCubit to prevent emit calls after closure
- add logging statements to track when operations are skipped due to state
- improve error handling for drive key validation and name loading
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/75ujs3jn5g0p8

PE-7868: refactor(drive attach): add state checks to prevent actions after unmount

---

lib/authentication/login/blocs/login_bloc.dart

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/5fmjene1neahg

PE-8133: fix(login): check if user is an arconnect profile before checking wallet version compatibility

---

lib/arns/domain/arns_repository.dart
lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
lib/blocs/fs_entry_info/fs_entry_info_state.dart
lib/blocs/shared_file/shared_file_cubit.dart
lib/blocs/shared_file/shared_file_state.dart
lib/components/components.dart
lib/components/copy_button.dart
lib/components/details_panel.dart
lib/components/drive_share_dialog.dart
lib/components/file_share_dialog.dart
lib/components/owner_field.dart
lib/components/profile_card.dart
lib/pages/shared_file/shared_file_page.dart

- Add OwnerField component to display file uploader with ArNS name/logo
- Show 'Uploaded By' field in details panel for shared files only
- Integrate ArNS primary name and profile logo lookup
- Display ar:// prefix for ArNS names with 28x28 logo
- Add copy wallet address functionality with standard 'Copied!' feedback
- Extract CopyButton as reusable component to reduce code duplication
- Fix owner address extraction from FileEntity before revision conversion
- Hide ArNS Name assignment field on share pages
- Style consistently with existing transaction ID fields
- Support ViewBlock link for both ArNS names and wallet addresses
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/7lgrqn9sr3nug

PE-8434: feat: add file uploader display with ArNS integration to share page

---

android/fastlane/metadata/android/en-US/changelogs/199.txt
pubspec.yaml

Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/007o9spm5v480

PE-8464: chore - bump version; add fastlane notes 

---

lib/app_shell.dart
lib/authentication/ardrive_auth.dart
lib/components/sync_failure_test_panel.dart
lib/l10n/app_en.arb
lib/sync/domain/cubit/sync_cubit.dart
lib/sync/domain/cubit/sync_state.dart
lib/sync/domain/repositories/sync_repository.dart
lib/sync/domain/sync_cancellation_token.dart
lib/sync/domain/sync_failure_simulator.dart
lib/sync/domain/sync_progress.dart
lib/user/repositories/user_repository.dart

fix: improve sync cancellation and UX during post-sync operations
- Add status messages for post-sync operations (ghost folders, licenses, transaction updates)
- Display descriptive messages instead of just percentages during final sync stages
- Reduce transaction status update timeout from 30s to 10s for better responsiveness
- Add 5s timeout for individual GraphQL calls to prevent blocking
- Fix cancellation exception propagation to ensure cancel modal always appears
- Add more frequent cancellation checks throughout post-sync operations
- Handle timeouts gracefully without showing error modals
- Ensure cancellation exceptions are re-thrown through try-catch blocks
The sync process now provides clearer feedback about what's happening during the
final stages (92-100%) and allows …

PE-8473: fix: sync process improvements

---

lib/blocs/upload/payment_method/view/upload_payment_method_view.dart
lib/components/drive_create_form.dart
lib/components/drive_rename_form.dart
lib/components/folder_create_form.dart
lib/components/payment_method_selector_widget.dart
lib/components/upload_form.dart
lib/l10n/app_en.arb
lib/pages/drive_detail/components/drive_explorer_item_tile.dart

- Remove blocking modal congestion warnings from auto-Turbo operations (folder/drive create/rename)
- Add non-blocking inline warning that only appears when AR payment method is selected
- Warning now shows below payment selector with localized text: 'Network congestion detected - uploads may be slower or fail'
- Eliminate unnecessary mempool API calls for operations that always use Turbo
- Support both dropdown and radio button payment selectors
- Ensure proper display in both light and dark modes
BREAKING CHANGE: Removes showCongestionDependentModalDialog from folder and drive operations <- these default to Turbo and the user cannot even spend AR and go direct to network anyway.
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:androi …

PE-8450: fix: improve UX for network congestion warnings
